### ISSUE TITLE
[建议]hooks可以配置到model相关的地方，而不是仅仅在table域

### ISSUE THREAD

**Issue by liuzhijun** [YaoApp/yao#101]
从Yao的设计中没有找到基于model的hook，但是在table中包含了很多类似的东西。
私以为hook有必要存在于model相关的纯逻辑中。
当然，存在table中也可以算做UI相关的hook。
参考：https://www.larashout.com/how-to-use-laravel-model-observers

**Comment by trheyi** [comment]
这样设计的主要目的是解耦，如仅做接口使用，可以忽略相关配置。

表格有一组现成的API可用。
https://github.com/YaoApp/docs-yao/tree/main/table/apis


```json
{
    "name": "列表",
    "version": "1.0.0",
    "decription": "列表",
    "bind": {    "model": "pet",     "withs": { "user": {}}   },
    "hooks": { },
    "apis": {},
    "columns": {},
    "filters": {},
    "list": {},
    "edit": {},
    "view": {}
}
```

**Comment by liuzhijun** [comment]
靠谱~！！我居然还写了很多scripts。。。

**Comment by trheyi** [comment]
可以建立一个表格，绑定一个模型，通过表格的 hooks 或指定 API处理 。  
表格可以理解为模型的一个实例，根据需要一个模型可以与多张表格关联。

**Comment by liuzhijun** [comment]
确实是可以的。
但是有个情况就是当UI在被限制的情况下，无法产生出符合表格API的接口调用的时候，表格就无法使用了。
如果不考虑接口的问题，表格的做法确实够用了，很酷~！
