### ISSUE TITLE
怎么在本地运行源码啊

### ISSUE THREAD

**Issue by coder-Yif** [YaoApp/yao#108]

**Comment by trheyi** [comment]
https://github.com/YaoApp/yao/actions/runs/2114243701/workflow

**Comment by thlz998** [comment]
https://github.com/YaoApp/yao
https://github.com/YaoApp/xun
https://github.com/YaoApp/gou
https://github.com/YaoApp/kun
https://github.com/rogchap/v8go


把这几个项目拉到同一个目录下

之后进入到yao的目录

执行 go run main.go 就可以了
