### ISSUE TITLE
您好 请问后续是否会有oa审批工作流支持？

### ISSUE THREAD

**Issue by importtao** [YaoApp/yao#117]

**Comment by MatrixAge** [comment]
Good idea. 开源版本的ERP制作中，其中会包含流程支持，包括但不限于OA审批模块。

**Comment by snowyu** [comment]
还缺事件驱动这块(CRUD记录前拦截(事件处理可以返回取消或更改执行), 以及CRUD后触发),  角色动态权限管理, 及用户与组织基础Model

* [node-red](http://nodered.org/)
* node-red port to golang: https://www.flogo.io/

**Comment by MatrixAge** [comment]
> 

如果你试着运行了demo，就知道这些功能都已经存在了。

**Comment by snowyu** [comment]
线上跑的Demo不是最新的?  文档中也没有提到Event, 只有 Process DataFlow Query.

建议有空写下架构文档,后端是什么架构,前端是什么架构,如何组织扩展?

一阴一阳为之道,大道至简,又生化万物. 加油吧.

**Comment by MatrixAge** [comment]
Process支持使用JS编写自定义处理器，这个是YAO的核心，一切都是Process，多个Process组成DataFlow，如果你真的对架构感兴趣的话，可以试着用一下，用了之后再来评价。

至于“架构文档”，很少有开源项目专门写架构文档详细介绍项目架构吧？我们又不是教育家和慈善家，负责开源还得负责“屎尿屁”，暂时没有这方面的打算，一个是因为在我们还没特别成熟的时候，说太多容易被别有目的的人“整体抄袭”，这是一个很现实的原因，还有一个我们确实没有精力去讲太多核心架构的东西，以后用的人多了会办YAO Conf，到时会讲一些实现细节。

现阶段我们更关注YAO的功能，而不是其他，如果你有阅读源码的能力，大概率不会问出上述问题。

说话如有冒犯请见谅。

**Comment by snowyu** [comment]
没啥, 我本职是架构,所以更关心此. 架构决定是否KISS. 如果架构一两句说不清楚,可能离至简还有些距离.  开源届项目太多,如果每一个都要review代码,精力实在不够,见谅,我的习惯是先看demo,再看文档和社区,最后code review.

后端应该是headless API,可谓阴, 前端引擎谓之阳.

功能反而是更次要的,核心引擎更重要,生万物的关键.

Process 太抽象了, RPC(Remote Procedure Call)标准协议非常多, 应该是围绕RPC作服务的扩展吧,这块比较值得推荐的是 https://moleculer.services/ 它的架构文档齐全,内核非常简单,扩展非常容易. 

这是我给一个很棒的低代码平台提的建议: https://github.com/steedos/steedos-platform/issues/1783 可供参考

开源就不应该畏惧COPY. 而应该是激励更多人JOIN.

所知越多,所觉越浅

**Comment by MatrixAge** [comment]
实用即美，说再多没法给用户带来价值也是白扯

**Comment by trheyi** [comment]
@snowyu  

道友你好，万物负阴而抱阳，**冲气以为和**。YAO 有更好的前后端结合方式。

YAO 源自海量的项目实践，YAO 架构灵感源于中国古建筑和周易，XGEN 前端架构乃是 @MatrixAge  梦中所得。

所以，欢迎讨论玄学。

文档新版发布后，继续完善，也欢迎PR一起改进。

Tips:

Process 也并非 YAO 所创   https://en.wikipedia.org/wiki/Flow-based_programming

**Comment by AbbetWang** [comment]
> Good idea. 开源版本的ERP制作中，其中会包含流程支持，包括但不限于OA审批模块。

请问，指的是那个开个开源版本
