### ISSUE TITLE
Yao web services mode

### ISSUE THREAD

**Issue by zo-sansen** [YaoApp/yao#119]
你好为什么我代码yao start，所以页面都是这个信息，没有页面

**Comment by alanjiang1129** [comment]
![image](https://user-images.githubusercontent.com/30771442/167974814-b58886f0-5886-4994-b7ba-6dedb1c7ec5e.png)
就所有url，不是api的，debug了一下，所有ui都是获取的这个方法
![image](https://user-images.githubusercontent.com/30771442/167975081-265897de-4298-4dba-8d3b-d9c96d8fcb51.png)

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/yao/blob/main/.github/workflows/release-linux.yml

参考这个，建议使用官网打包好的Yao。

**Comment by alanjiang1129** [comment]
这个是要改linux的配置吗？我是在本机Ubuntu 20.04 运行的，我不是想要用打包好的 yao 运行程序，我是想学习一下代码，自己在debug，但是本地运行的goland ide中yao start就是不行诶

**Comment by alanjiang1129** [comment]
想问下是不是用的 umijs 做的ui框架，是怎么在yao里面运行的啊

**Comment by alanjiang1129** [comment]
这个不是 .github 文件夹下的文件嘛，我下载的代码应该自带的吧

**Comment by MatrixAge** [comment]
参考上述CI配置。

**Comment by thlz998** [comment]
在自己打包代码的话可以参考下Makefile里的release流程，你这里没有出现后台项目可能是打包的时候没有把管理端的静态文件打包进去。

可以参考下边的步骤，重新编译打包一下



```
	mkdir -p dist/release
	mkdir .tmp

#	Building UI
	git clone https://github.com/YaoApp/xgen.git .tmp/ui
	sed -ie "s/url('\/icon/url('\/xiang\/icon/g" .tmp/ui/public/icon/md_icon.css
	cd .tmp/ui && yarn install && yarn build

#	Packing
	mkdir -p .tmp/data
	cp -r .tmp/ui/dist .tmp/data/ui
	cp -r yao .tmp/data/
	go-bindata -fs -pkg data -o data/bindata.go -prefix ".tmp/data/" .tmp/data/...
	rm -rf .tmp/data
	rm -rf .tmp/ui

#   Making artifacts
	mkdir -p dist
	CGO_ENABLED=1 CGO_LDFLAGS="-static" go build -v -o dist/release/yao
	chmod +x  dist/release/yao
```
