### ISSUE TITLE
yao现在或以后能否支持自定义实现中间件？

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#122]

**Comment by trheyi** [comment]
guard 可以指定为一个或多个处理器  

https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.9.2-linux-amd64

**Comment by liushuainice** [comment]
有使用说明或者例子么？当做guard的处理器方法，要怎么写？

**Comment by trheyi** [comment]
```json
{
        "path": "/user/:id",
        "method": "GET",
        "guard": "scripts.user.Auth",
        "process": "flows.user.find",
        "in": [],
        "out": {
            "status": 200,
            "type": "application/json"
        }
    }

```

`/scripts/user.js`

```javascript
function Auth(path, params, query, payload, headers) {
 var user = Process("session.Get", "user");

  if (!user) {
    throw new Exception("未登录", 403);
  }

return 
}
```

**Comment by liushuainice** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/49874458/171102005-10267ae3-f9cc-4fd2-bf76-6779c8e74b65.png">
![Uploading image.png…]()

**Comment by liushuainice** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/49874458/171102078-cb35a51c-4946-4dc0-aba3-34374e484e34.png">

**Comment by liushuainice** [comment]
<img width="245" alt="image" src="https://user-images.githubusercontent.com/49874458/171102119-7f26e895-36fc-4f72-8f91-8e77acf88be6.png">
