### ISSUE TITLE
docs errors

### ISSUE THREAD

**Issue by xiaobinqt** [YaoApp/yao#123]
![image](https://user-images.githubusercontent.com/23259661/170966419-b9374453-4790-46ea-9d3c-45534eb684aa.png)

这里是`apis` 目录吧?

[//]: # (![image]&#40;https://user-images.githubusercontent.com/23259661/170967569-d6e45c3a-15fa-4749-8a45-99a3f1729198.png&#41;)

[//]: # (这里的 `xiang` 应该不需要了吧 ?)

[//]: # (![image]&#40;https://user-images.githubusercontent.com/23259661/170967723-791d6ba3-28cc-433f-a3a7-b03e32bcd431.png&#41;)

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/components-doc-zh-CN

收到反馈！你也可以提一个PR。

**Comment by xiaobinqt** [comment]
> https://github.com/YaoApp/components-doc-zh-CN
> 
> 收到反馈！你也可以提一个PR。

好的。
