### ISSUE TITLE
When using the tree component, instead of passing the selected ID to me, it passes a string such as 0-1-1

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#128]
<img width="623" alt="1655085780845" src="https://user-images.githubusercontent.com/34130829/173266511-1453ac93-5458-40dd-8755-2f13b180e240.png">
<img width="530" alt="1655085827577" src="https://user-images.githubusercontent.com/34130829/173266589-ca0f9657-ab66-45d7-932a-83262fd12eef.png">

**Comment by MatrixAge** [comment]
https://ant.design/components/tree-cn/
