### ISSUE TITLE
xiang.network.Post 怎么调用呢

### ISSUE THREAD

**Issue by dayhappy2012** [YaoApp/yao#129]
![image](https://user-images.githubusercontent.com/47685606/173314034-d0840658-758f-4de1-9cab-b4e5350f8694.png)
文档点进去 500 了

**Comment by MatrixAge** [comment]
@QJAutumn

**Comment by QJAutumn** [comment]
所有的请求都可以使用以下方法:
var response = Process("xiang.network.Send", "PATCH", url, params, body, header);
var response = Process("xiang.network.Send", "GET", url, params, body, header);
var response = Process("xiang.network.Send", "POST", url, params, body, header);
var response = Process("xiang.network.Send", "DELETED", url, params, body, header);
