### ISSUE TITLE
自定义 js-处理器  报错!!

### ISSUE THREAD

**Issue by dayhappy2012** [YaoApp/yao#130]
![image](https://user-images.githubusercontent.com/47685606/173315162-a8ba5f20-d810-4eb5-b1f6-f7fa11d74717.png)

![image](https://user-images.githubusercontent.com/47685606/173315279-43d198d8-c19d-42f2-b8e1-16fe68ead67d.png)

这种有什么解决方案吗？ 或者说 xiang.network.Post 是实现它的方式？

**Comment by MatrixAge** [comment]
服务端不存在XHR。

**Comment by QJAutumn** [comment]
可以使用 xiang.network.PostJSON

var response = Process("xiang.network.PostJSON", url, {"user":"foo","name":"bar"}, {
    Authorization: "Bearer " + access_token,
  });

**Comment by dayhappy2012** [comment]
@QJAutumn 谢谢
