### ISSUE TITLE
我想创建一个父节点，但是找不到相关文档

### ISSUE THREAD

**Issue by china-bigcloud** [YaoApp/yao#131]
当新建菜单时，没有选项可以设置父节点，于是我尝试在界面点击父节点栏的“-”，然后键入父节点名称后我的选项消失了，所以我不知道该如何配置了。
![image](https://user-images.githubusercontent.com/25924469/174019736-0f11f766-c4db-4dae-b411-1bde0adc2f98.png)
![image](https://user-images.githubusercontent.com/25924469/174019786-e84c3f14-c795-46b2-8b15-9e402dd44945.png)
![image](https://user-images.githubusercontent.com/25924469/174019847-249b689d-970a-447e-a8f5-d9068f9eecc7.png)

**Comment by trheyi** [comment]
https://github.com/YaoApp/demo-wms/tree/main/cloud/flows/init 
可以使用FLOW创建菜单，参考上例
运行 
```bash
yao run flows.menu
```
