### ISSUE TITLE
新建Menu 提示尚未加载

### ISSUE THREAD

**Issue by smallfish01** [YaoApp/yao#132]
您好，
我新建了一个menu, 退出重新登录后可以看到新建的menu,但是当我点击该Menu,提示Menu尚未加载，重新启动容器，重新执行：
yao migrate
yao start
也是同样问题。

谢谢。

**Comment by QJAutumn** [comment]
您menu表中对应字段path是tables目录下对应的table文件,可能是您的文件没有添加,xxx.tab.json文件然后应该就好了
