### ISSUE TITLE
文档 上存在错误？

### ISSUE THREAD

**Issue by dayhappy2012** [YaoApp/yao#140]
![image](https://user-images.githubusercontent.com/47685606/179437465-d42fc02e-9922-48fb-b993-12c8201013b9.png)

**Comment by wangyu-geek** [comment]
[为什么选择yao](https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/c.%E4%B8%BA%E4%BB%80%E4%B9%88%E9%80%89%E6%8B%A9Yao)

是万物互联，不是外物互联

**Comment by QJAutumn** [comment]
感谢大家的指出,已经修复
