### ISSUE TITLE
创建数据模型后，未编写接口，会自动生成默认的 CRUD API ？

### ISSUE THREAD

**Issue by YahuiAn** [YaoApp/yao#144]
根据 [入门指南](https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/a.%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97) 执行后
```bash
yao init
yao migrate
yao run flows.setmenu
yao start
```
登录界面发现 pet 可以正常显示和编辑，但是此时我还未编辑任何文件，即只有 ``pet.mod.json`` 和 ``pet.tab.json`` 并没有 ``pet.http.json`` 文件

我想问问在我未编写 ``apis`` 文件时，会自动生成默认的 CRUD API 吗，如果会的话，默认的 API 都有哪些，支持哪些参数呢？

我在目前的文档中未找到相关答案。🙏

**Comment by YahuiAn** [comment]
补充一下：``yao start`` 时打印的 API List 中也没有相关的接口

**Comment by MatrixAge** [comment]
自动生成的规则我们将会在1.0发布之后 开始设计，基于模型自动生成确实可能带来方便

**Comment by YahuiAn** [comment]
期待期待 👍 

[数据表格管理接口 apis 文档中写到](https://yaoapps.com/doc/f.%E5%8F%82%E8%80%83%E6%89%8B%E5%86%8C/g.%E6%95%B0%E6%8D%AE%E8%A1%A8%E6%A0%BC#2.3%20%E6%95%B0%E6%8D%AE%E8%A1%A8%E6%A0%BC%E7%AE%A1%E7%90%86%E6%8E%A5%E5%8F%A3%20,[object%20Object])
> 如设置绑定数据模型，自动根据模型信息生成数据管理 API

想问问目前版本 0.9.2 自动生成 API 的规则有文档或者代码吗？

**Comment by MatrixAge** [comment]
只要写了在table文件夹下写了对应model的table描述，就会有对应的接口生成，参考demo，生成了pet的CRUD接口.

**Comment by YahuiAn** [comment]
感谢感谢~
总结一下就是，如果只想要基本的 CRUD 接口，就不用写 ``apis`` 描述，用默认生成的就行，如果有拓展，定制的需求，就在 ``apis`` 中编写新的描述即可。

不过目前 [数据模型](https://yaoapps.com/doc/d.%E5%A4%84%E7%90%86%E5%99%A8/b.%E6%95%B0%E6%8D%AE%E6%A8%A1%E5%9E%8B) 中的文档点击后都是 500，所以无法得知这些接口具体如何传参数 😭

**Comment by MatrixAge** [comment]
我们开放了一些demo，你可以在yaoapp组织中找到这些仓库，看看怎么写的，大概就知道怎么用了。
