### ISSUE TITLE
可以去掉用户登录模块吗？

### ISSUE THREAD

**Issue by YahuiAn** [YaoApp/yao#145]
我有一个非常简单的应用，希望可以去掉用户登录模块，直接显示我的应用主页，研究了一番发现貌似用户系统是 ``xiang`` 内置的，``app.json`` 中只有控制是否显示 user 的功能，请问有相关的实现方法吗？ 🙏

**Comment by QJAutumn** [comment]
可以使用免密登录功能,
参考案例:https://demo-crm.yaoapps.com/xiang/login/admin?autoLogin=true
