### ISSUE TITLE
系统是ubantu 22，运行curl -fsSL https://website.yaoapps.com/install.sh | bash报错

### ISSUE THREAD

**Issue by hithotmay** [YaoApp/yao#151]
mv：无法获取'tmp/yao-0.9.2'的文件状态(stat):没有那个文件或目录

**Comment by QJAutumn** [comment]
试试使用 wget https://release-sv.yaoapps.com/archives/yao-0.10.1-linux-arm64 然后把这个制品名称改为yao 放到/usr/local/bin 目录,chmod+x yao
