### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by inluxc** [YaoApp/yao#152]
Do you have any translation service so we can use to translate the app, there is a lot of keys not translated.

**Comment by MatrixAge** [comment]
We will pubnish a new version that supporting i18n at next week. Your can define translating keys for your app at that time.

**Comment by trheyi** [comment]
The new version is available via the link below:

https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.10.0-darwin-amd64  Mac 
https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.10.0-darwin-arm64   Mac M1/M2
https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.10.0-linux-amd64  Linux


Language packs are placed in the langs directory：
https://github.com/YaoApp/gou/blob/main/tests/app/langs/zh-cn/global.yml  

Language variables are prefixed with `::` 
https://github.com/YaoApp/gou/blob/main/tests/app/models/demo.mod.json

**Comment by Barceloch** [comment]
I'm trying translate to "es" the login page tags (ex. Account: Usuario, Password: Contraseña) adding /path/myapp/langs/es/global.yml, then in the .env file: YAO_LANG="es" but not working...

Am I doing something wrong, or this functionality is not available yet?

**Comment by MatrixAge** [comment]
Only zh_cn & en_us support yet.
