### ISSUE TITLE
文档里关于插件的内容取消了，请问现在还支持插件吗

### ISSUE THREAD

**Issue by findziliao** [YaoApp/yao#155]

**Comment by trheyi** [comment]
插件还是支持的，文档稍后整理过来。 

目前插件的使用率不高。因为可以用以下两种更方便的方式替代:

1. 使用 JavaScript 实现处理器。
2. 修改 Yao 代码，直接在引擎内添加处理器。

参考文档:

添加处理器:

https://yaoapps.com/doc/%E4%BB%8B%E7%BB%8D/YAO%E6%9E%B6%E6%9E%84%E8%A7%A3%E6%9E%90#%E6%B7%BB%E5%8A%A0%E5%A4%84%E7%90%86%E5%99%A8

编写处理器: 
https://yaoapps.com/doc/%E8%BF%9B%E9%98%B6/%E7%BC%96%E5%86%99%E5%A4%84%E7%90%86%E5%99%A8

源码编译:
https://yaoapps.com/doc/%E4%B8%93%E5%AE%B6/%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91
