### ISSUE TITLE
yao migrate error

### ISSUE THREAD

**Issue by lovefishs** [YaoApp/yao#156]
根据官网文档 [创建数据模型](https://yaoapps.com/doc/%E5%9F%BA%E7%A1%80/%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E6%A8%A1%E5%9E%8B#%E5%88%9B%E5%BB%BA%E6%95%B0%E6%8D%AE%E6%A8%A1%E5%9E%8B) 想要执行 `yao migrate -n user` 创建数据表 `user`，但是不成功，报错信息如下

```bash
$ yao migrate -n user
Fatal: runtime error: invalid memory address or nil pointer dereference
```

项目使用 `yao init` 命令初始化而得，环境信息如下

- yao version: 0.10.1-b538fd87471d
- go version: go1.19 darwin/amd64
- system: macOS Monterey 12.5

**Comment by trheyi** [comment]
user.mod.json  这个文件的内容是啥，应该是有字段写错了。

**Comment by lovefishs** [comment]
@trheyi 谢谢你的提醒，我再检查了一下 json 字段，是有写错的，问题已经解决，感谢！
