### ISSUE TITLE
setup ok, run crm demo throw error when password is not correct

### ISSUE THREAD

**Issue by helperAI** [YaoApp/yao#157]
{"message":"登录密码错误%!(EXTRA string=xiang@iqka.com)","code":403,"context":null}
/home/runner/work/yao/kun/exception/exception.go:114 (0x10ed59d)
/home/runner/work/yao/yao/user/user.go:60 (0x10ed4be)
/home/runner/work/yao/yao/user/process.go:41 (0x10ebaa4)
/home/runner/work/yao/gou/process.go:21 (0xdc642f)
/home/runner/work/yao/gou/api.http.go:187 (0xdc6426)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x99e9e1)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x99e9cc)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x10799b7)
/home/runner/work/yao/yao/service/middleware.go:32 (0x1079848)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x99e9e1)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/recovery.go:99 (0x99e9cc)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x99db06)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/logger.go:241 (0x99dae9)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/context.go:168 (0x99cbd0)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:555 (0x99c838)
/home/runner/go/pkg/mod/github.com/gin-gonic/gin@v1.7.7/gin.go:511 (0x99c371)
/opt/hostedtoolcache/go/1.18.2/x64/src/net/http/server.go:2916 (0x75ff1a)
/opt/hostedtoolcache/go/1.18.2/x64/src/net/http/server.go:1966 (0x75af16)
/opt/hostedtoolcache/go/1.18.2/x64/src/runtime/asm_amd64.s:1571 (0x473b00)

**Comment by trheyi** [comment]
这是正常的反馈结果
