### ISSUE TITLE
初始bug，跑不起来

### ISSUE THREAD

**Issue by whereiscode** [YaoApp/yao#162]
go: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03 (replaced by ../gou): reading ../gou/go.mod: open /Users/xxx/go/gou/go.mod: no such file or directory

**Comment by trheyi** [comment]
https://yaoapps.com/doc/%E4%B8%93%E5%AE%B6/%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91
