### ISSUE TITLE
编译错误 go1.18.3 darwin/amd64

### ISSUE THREAD

**Issue by longkeyy** [YaoApp/yao#191]
git clone https://github.com/YaoApp/yao.git
make

==================================================================================

cmd/dump.go:15:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
cmd/start.go:16:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
network/request.go:12:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
main.go:6:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
table/table.go:14:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
app/app.go:5:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
query/query.go:5:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
query/query.go:6:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:9:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:10:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
cert/cert.go:7:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
cmd/start.go:17:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
cmd/start.go:18:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
cmd/start.go:19:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
widget/widget.go:11:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:11:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
cmd/dump.go:16:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
cmd/start.go:20:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
cmd/inspect.go:5:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
cmd/inspect.go:6:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
xfs/process.go:18:2: github.com/yaoapp/xun@v0.9.0: replacement directory ../xun does not exist
share/db.go:6:2: github.com/yaoapp/xun@v0.9.0: replacement directory ../xun does not exist
api/api.go:8:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:9:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:10:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:11:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
config/config.go:11:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
api/api.go:9:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
share/api.go:14:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
share/api.go:15:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
share/db.go:6:2: github.com/yaoapp/xun@v0.9.0: replacement directory ../xun does not exist
share/api.go:8:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
app/app.go:5:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:9:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:10:2: github.com/yaoapp/gou@v0.0.0-20211120135538-e5387704eb03: replacement directory ../gou does not exist
share/api.go:11:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
app/app.go:6:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
config/config.go:12:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
app/app.go:7:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
share/api.go:15:2: github.com/yaoapp/kun@v0.9.0: replacement directory ../kun does not exist
xfs/process.go:18:2: github.com/yaoapp/xun@v0.9.0: replacement directory ../xun does not exist
share/db.go:6:2: github.com/yaoapp/xun@v0.9.0: replacement directory ../xun does not exist

**Comment by trheyi** [comment]
https://yaoapps.com/doc/%E4%B8%93%E5%AE%B6/%E6%BA%90%E7%A0%81%E7%BC%96%E8%AF%91

Golang 1.19.2
