### ISSUE TITLE
请问表的多对多关联关系是否支持？

### ISSUE THREAD

**Issue by cncowboy** [YaoApp/yao#194]

**Comment by trheyi** [comment]
https://yaoapps.com/doc/%E8%BF%9B%E9%98%B6/%E7%BC%96%E5%86%99%E5%A4%84%E7%90%86%E5%99%A8
可以通过中间表关联，再复杂的查询可以编写处理器实现逻辑

**Comment by cncowboy** [comment]
谢谢回复！
