### ISSUE TITLE
Login Credentials Demo

### ISSUE THREAD

**Issue by jijothic** [YaoApp/yao#2]
what are the login credentials for the demo ?

**Comment by trheyi** [comment]
Thanks for the feedback, we have reset the data and can try it now. The demo data will be cleared every hour.
https://demo-crm.yaoapps.com/xiang/login/admin?autoLogin=true

You can also try to install yao and then run this demo locally
https://yaoapps.com/en-US/doc/a.Introduction/a.Getting%20Started

感谢反馈，我们已经重置了数据，现在可以在试下。demo 的数据将每小时清空一次。
https://demo-crm.yaoapps.com/xiang/login/admin?autoLogin=true

你也可以尝试安装yao，然后在本地运行这个 demo
https://yaoapps.com/en-US/doc/a.Introduction/a.Getting%20Started

**Comment by jijothic** [comment]
Thank you :)
