### ISSUE TITLE
后期项目表字段变动该如何处理

### ISSUE THREAD

**Issue by nntx** [YaoApp/yao#21]
比如追加新字段，不能使用 migrate ，那么如何来更新字段。

**Comment by veryy** [comment]
修改json文件

**Comment by nntx** [comment]
@veryy 直接修改 json 文件,表是不会变化的,

>  Migrate is not allowed on production mode.

如果强制 migrate 那么就会清空数据, 是否表示字段中途是不能变化(追加,删除)

**Comment by veryy** [comment]
用sqlite修改db文件试试

**Comment by veryy** [comment]
然后json也修改一下

**Comment by nntx** [comment]
直接改数据库是吧，明白了。

有空我打算写个追加字段的功能 :)
