### ISSUE TITLE
Question: 既然整个应用是基于json，那为啥不把json的构建放到前台来做，毕竟写json也费事

### ISSUE THREAD

**Issue by BeanWei** [YaoApp/yao#22]
RT

**Comment by MatrixAge** [comment]
JSON可视化主要针对低端开发者，对于我们自身的业务来讲，收益率太低，优先级不高，会做，但不是现在。

**Comment by BeanWei** [comment]
还有个问题，基于json怎么去做业务逻辑呢，比如crud的hook

**Comment by MatrixAge** [comment]
https://yaoapps.com/doc/b.%E5%9F%BA%E7%A1%80%E7%89%B9%E6%80%A7/b.%E7%BC%96%E5%86%99%E6%8E%A5%E5%8F%A3
Yao提供了很多内置处理器，直接可以用来CRUD，如果想要扩展更多逻辑，可以使用flow，flow支持调用JS。

**Comment by BeanWei** [comment]
感谢耐心回复，感觉这里面充满了ideas，哈哈:) 

请问下有微信交流群么？

**Comment by trheyi** [comment]
@BeanWei 感谢反馈，下一版本，面向国内推广时会创建微信群。
