### ISSUE TITLE
application.log里缺少sql语句日志

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#233]
<img width="985" alt="image" src="https://user-images.githubusercontent.com/49874458/198456687-222308ce-8d11-4b1a-ac0c-86573afcb6bd.png">

在demo-crm项目的flows/chart里的处理器,如截图中的写法,日志文件里不会产生sql语句日志

**Comment by liushuainice** [comment]
<img width="1031" alt="image" src="https://user-images.githubusercontent.com/49874458/198495358-bf64db54-70c0-4811-bd62-8e93f4739cb9.png">
刚刚发现在query里加上debug字段可以在控制台上看到sql,但日志文件里还是没有

**Comment by helperAI** [comment]
我觉得所有的model，flow和table中的与sql相关内容全部需要一个：debug:true的开关把sql的拼接写入日志，方便调试。因为目前的sql语句基本是json文件定义的。不熟悉的时候经常找不到原因为何数据返回不是所需要的。
