### ISSUE TITLE
执行sql语句的 stmt 疑问

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#236]
<img width="491" alt="image" src="https://user-images.githubusercontent.com/49874458/198497713-f9b66506-dedb-4da7-ab13-83a8de1e1f2c.png">
在demo-crm里看到了执行sql语句的例子,只要删除数据的操作,这块还有其他资料么?
我想执行增改查的sql语句,支持么?要怎么写?

**Comment by wwsheng009** [comment]
query.sql调用的是数据库的exec操作，只要不需要获取返回值的sql语句都可以这样执行
