### ISSUE TITLE
docker 部署后，ui页面默认用户名，密码是？

### ISSUE THREAD

**Issue by znrun** [YaoApp/yao#25]
docker 部署后，ui页面默认用户名，密码是？

**Comment by trheyi** [comment]
参考这个文档：
https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/a.%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97#%E7%AC%AC%E4%B8%89%E6%AD%A5:%20%E5%90%AF%E5%8A%A8%E6%9C%8D%E5%8A%A1
