### ISSUE TITLE
docker yao安装成功后，找不到本地项目，页面也打不开

### ISSUE THREAD

**Issue by xiangcs** [YaoApp/yao#27]

**Comment by xinde** [comment]
你可以把你的环境及安装步骤发出来，这样能很快解决问题

**Comment by xiangcs** [comment]
> 你可以把你的环境及安装步骤发出来，这样能很快解决问题

好的 

系统是win10
操作步骤，按照Yao的安装调试不走，<Project root>改为d，放在了d盘，但是去D盘里没找到文件
![image](https://user-images.githubusercontent.com/16007733/157152934-19c3f02e-581d-4fa4-addf-c4c640449708.png)

**Comment by xiangcs** [comment]
上面的几步操作都没问题，安装成功了，就是页面打不开

**Comment by xinde** [comment]
> 上面的几步操作都没问题，安装成功了，就是页面打不开

默认是没有项目文件的，需要进入容器里 
```
yao init
yao start
```

**Comment by xiangcs** [comment]
能不能像IDE一样进行开发呢？

**Comment by xinde** [comment]
可以在docker外部通过vs code等编辑器编辑json配置等，回到docker里重启。作者提供docker也是方便初学者，避免安装一堆烦锁步骤。可以再仔细看看文档。

**Comment by xiangcs** [comment]
好的 看了好几遍，没看懂在哪里编辑文件[笑哭]

我再看看，感谢感谢

**Comment by trheyi** [comment]
https://www.jianshu.com/p/889885e75de8 参考docker相关文档。 @xiangcs
