### ISSUE TITLE
菜单获取接口yao.app.menu返回数据结构不一致导致UI报错

### ISSUE THREAD

**Issue by wwsheng009** [YaoApp/yao#280]
新版本接口yao.app.menu 返回的数据结构应该包含了setting与items两个字段，但是此flow内部调用的接口models.xiang.menu.get却直接返回了旧版本数据格式菜单数组。

比如以下两个项目返回的结构就不一致
项目https://github.com/YaoApp/yao-dev-app/blob/main/flows/app/menu.flow.json
与项目https://github.com/YaoApp/demo-app/blob/main/flows/app/menu.flow.json

另外使用用yao-admin直接生成的项目也是直接返回的菜单数组。

**Comment by QJAutumn** [comment]
使用0.10.2版本的Yao
