### ISSUE TITLE
Demo link is not working

### ISSUE THREAD

**Issue by Wyfy0107** [YaoApp/yao#30]
This demo link in readme: https://demo-crm.yaoapps.com/xiang/login/admin?autoLogin=true is not working. The page is continuously refreshing

**Comment by trheyi** [comment]
Thanks for the feedback.
The demo is refresh data every hour, It may be refreshing when you visit. try it later.

**Comment by sihq** [comment]
Demo links are broken - refresh loop.

**Comment by theobouwman** [comment]
When I run a init project with docker and go to the dashboard it is indeed a refresh loop

**Comment by trheyi** [comment]
yao migrate
yao run flows.demo.fake  
yao start 

Add test data and try again

@theobouwman

**Comment by trheyi** [comment]
@sihq  Have reset the data manually, it should be ok

**Comment by theobouwman** [comment]
@trheyi 
```
root@8f7aab93e11c:/data/app# yao run flows.demo.fake
Run: flows.demo.fake
Fatal: Flow:demo.fake; 尚未加
```

**Comment by trheyi** [comment]
https://github.com/YaoApp/demo-crm    
This repo is the demo of CRM,  you can check out and put it into /data/app, then run 

```bash
cd /data/app
yao migrate
yao run flows.demo.fake
yao start
```


create a new project with the sample, try 

```bash
mkdir /data/test
cd /data/test 
yao init
yao migrate && yao run flows.setmenu
yao start

```

**Comment by theobouwman** [comment]
Nope not working @trheyi still having the endless loop

**Comment by trheyi** [comment]
@theobouwman  Has the test data been loaded successfully?

**Comment by bradley-r-martin** [comment]
Why was this closed the links are still in a refresh loop ?
