### ISSUE TITLE
图表展示页面

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#304]
图表展示页面(自由拼接页面也是)中使用展示数量的组件:似乎不能展示小数,pet_count为小数的时候,会自动四舍五入,大于0.5的会变成1,小于0.5的会变成0
`  "宠物数量": {
        "bind": "pet_count",
        "link": "/x/Table/pet",
        "view": {
          "type": "Number",
          "props": { "unit": "个" }
        }
      },`

![1672810234076](https://user-images.githubusercontent.com/34130829/210490358-533ea3f8-d059-4902-8b39-5f0e5829a2cb.png)

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/210538063-51d4393c-3f49-40d7-8707-1998ed2fb6ce.png)
https://github.com/YaoApp/demo-app/blob/main/charts/dashboard.chart.json
![image](https://user-images.githubusercontent.com/25472851/210538218-7a39f7a0-add6-41a8-b6ce-c51d83392c21.png)

**Comment by MatrixAge** [comment]
遇到这种先看文档。

**Comment by QJAutumn** [comment]
> 遇到这种先看文档。

sorry,打扰了
