### ISSUE TITLE
二级菜单选中问题

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#305]
xgen-dev-app项目中 ,当前选中的菜单为: 编辑英雄,但是图标高亮的为:英雄管理1 ,点击其他的菜单高亮不会切换
![1672811471785](https://user-images.githubusercontent.com/34130829/210492440-ca7a1c9c-345e-4895-9fae-4f63f1a3719a.png)

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/xgen/commit/8e942942120fad3aad70c054f3c9c8f11d5b7728

**Comment by QJAutumn** [comment]
最新版本[版本](https://github.com/YaoApp/yao/suites/10281800299/artifacts/505034026)又出现这个问题了

**Comment by MatrixAge** [comment]
xgen-dev-app正常

**Comment by MatrixAge** [comment]
线上例子 菜单和相关页面模型不匹配 会干扰问题排查 建议换成和xgen-dev-app项目文件保持完全一致

**Comment by QJAutumn** [comment]
> 线上例子 菜单和相关页面模型不匹配 会干扰问题排查 建议换成和xgen-dev-app项目文件保持完全一致

是一模一样的

**Comment by QJAutumn** [comment]
已经修复

**Comment by QJAutumn** [comment]
已经修复
