### ISSUE TITLE
[List动态列表部分按钮隐藏] LIst动态列表按钮支持自定义显示或者隐藏

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#307]
## 需求背景
![1673311956368](https://user-images.githubusercontent.com/34130829/211437517-a7644759-7a24-4d9b-866f-07147de90363.png)

动态列表【List】自带4个按钮,有时候用户只需要一个新增同级别的列表按钮,不需要添加子集的按钮,能否设置几个属性把List的那几个可以自定义是否显示/隐藏

### 我遇到的问题
无法隐藏用户不需要的按钮,这样用户添加数据的时候容易造成数据不正确

## 提案

每个按钮增加是否展示/隐藏配置,设置
比如:
隐藏添加按钮:`hide_add:true`
隐藏添加子集按钮:`hide_children:true`

```json
      "动态表单": {
        "bind": "categories",
        "view": {},
        "edit": {
          "type": "List",
          "props": { "name": "category", "showLabel": false,"hide_add":true } //隐藏对应的按钮
        }
      }
```

## 额外补充

暂无

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/211492668-bcb445f6-89d0-4035-82db-c96e5c4399a2.png)

默认不支持children，通过`"hasChildren": true` 开启

**Comment by QJAutumn** [comment]
ok
