### ISSUE TITLE
[List动态表单删除按钮问题] 动态表单删除按钮问题

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#308]
## 相关截图（必需）
![1673314544379](https://user-images.githubusercontent.com/34130829/211441945-90e9fcb7-e500-4113-a79a-a18b5b7aa99c.png)
![1673314641907](https://user-images.githubusercontent.com/34130829/211442111-8afe9af1-5faf-4db5-bdbc-fd9cfd2bcb44.png)

## 最小可复现例子（必需）
[仓库地址](https://github.com/QJAutumn/List-Bug)
git克隆仓库`https://github.com/QJAutumn/List-Bug.git`

访问[http://127.0.0.1:5099/admin/login/admin](http://127.0.0.1:5099/admin/login/admin)
账号:[xiang@iqka.com](mailto:xiang@iqka.com) 
密码:A123456p+

## 复现步骤

1. 克隆代码执行`yao migrate && yao run scripts.demo.Data`,然后执行`yao start`
2. 访问`http://127.0.0.1:5099/admin/login/admin`
3. 账号:[xiang@iqka.com](mailto:xiang@iqka.com)  密码:A123456p+
4. 点击左边【列表】菜单-->点击List列表的随便一个删除按钮
![1673316965443](https://user-images.githubusercontent.com/34130829/211446684-158f06d8-3ead-4454-a5dd-5161e9cc9bb2.png)

**Expected behavior** 1. 2.

## Context

- **Yao Version( 0.10.3 )[下载地址](https://github.com/YaoApp/yao/suites/10189972221/artifacts/498706194)**:
- **Xgen Version( Build Info:time:2023-01-05T00:45:08+00:00|version:1.2.0)**:
- **Linux虚拟机**:

**Comment by MatrixAge** [comment]
重新打包一份，例子看 https://github.com/YaoApp/xgen-dev-app

**Comment by QJAutumn** [comment]
好了,没问题了

**Comment by QJAutumn** [comment]
这个问题又出现了:
在【编辑】有数据的时候,find返回的List数据有两条:点击了List里面的任意一个删除的按钮后,他把所有的数据都删除了,并且添加数据项按钮也不能点击了

不知道是不是我的用法不正确或者是数据格式不正确,我返回的数据为:

```
[
    {
        "id": 1,
        "number": 200,
        "price": 100,
        "type": "a"
    },
    {
        "id": 2,
        "number": 400,
        "price": 300,
        "type": "b"
    }
]
```

### 相关截图
![1675421770982](https://user-images.githubusercontent.com/34130829/216585920-31948982-1384-4603-a8c3-ab095187281b.png)

![1675422204855](https://user-images.githubusercontent.com/34130829/216587783-c88dac87-b51b-46b8-82e5-38149e5fbb7e.png)

### 最小可复现例子
仓库地址 : [地址](https://github.com/YaoApp/bug-check)

### 本地步骤 
克隆代码,然后执行:
yao migrate --reset
yao run scripts.init.setData
yao start
访问http://127.0.0.1:5099/admin/login/admin
账号:[xiang@iqka.com](mailto:xiang@iqka.com)
密码:A123456p+

### 线上步骤 

线上访问地址:
https://bug-check.iqka.com/admin/login/admin
账号:[xiang@iqka.com](mailto:xiang@iqka.com)
密码:A123456p+

如图:点击左边【列表】菜单-->点击List列表的随便一个删除按钮

![1675422482702](https://user-images.githubusercontent.com/34130829/216588701-3c3b45d1-ff2d-4fd3-acb8-51c965442b75.png)
### 版本信息
Yao Version( 0.10.3 )[下载地址](https://github.com/YaoApp/yao/suites/10758316822/artifacts/540118029):
Xgen Version( "Built Info" content="time:2023-02-03T10:00:02+00:00|version:1.4.0"):
Linux虚拟机:

**Comment by MatrixAge** [comment]
回传的数据和保存的数据不一致导致的，不能丢弃 selected和chonsen字段，这个渲染时要用到。

**Comment by QJAutumn** [comment]
###最新发现
 是这个id的问题,我把id改成数字就会这样,改成下划线字母加数字的就正常了
 `_8sFX5IN-bg98ZzEqFMOp91675490468028`
```
[
    {
        "id": "_8sFX5IN-bg98ZzEqFMOp91675490468028",
        "number": 200,
        "price": 100,
        "type": "a"
    },
    {
        "id": "_8sFX5IN-bg98ZzEqFMOp91675490468038",
        "number": 400,
        "price": 300,
        "type": "b"
    }
]
```

**Comment by MatrixAge** [comment]
> ### 最新发现
> 这个id有问题,我把id改成数字就会这样,改成下划线字母加数字的就正常了 `_8sFX5IN-bg98ZzEqFMOp91675490468028`
> 
> ```
> [
>     {
>         "id": "_8sFX5IN-bg98ZzEqFMOp91675490468028",
>         "number": 200,
>         "price": 100,
>         "type": "a"
>     },
>     {
>         "id": "_8sFX5IN-bg98ZzEqFMOp91675490468038",
>         "number": 400,
>         "price": 300,
>         "type": "b"
>     }
> ]
> ```

这里面包含一些逻辑，之前和平哥对过，具体的处理方式，问一下平哥。
