### ISSUE TITLE
[$on:change] 返回的setting不起作用

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#309]
## 组件使用`$on:change`的时候,返回了的`setting`好像没有起作用,不知道是哪里没有配置对,还是我的用法不对
![1673319295455](https://user-images.githubusercontent.com/34130829/211451328-07d44652-8b00-4bb8-ac97-e5f37b773d2d.png)

## 相关截图（必需）

1. 【住院天数】组件使用`onChange`组件

![1673319377140](https://user-images.githubusercontent.com/34130829/211451482-c634906b-c0c2-4b5e-82c0-f071ca7750c1.png)

2. `onChange`返回的字段列表`setting.form.sections.columns`只返回了三列的字段, `setting.fields.form.columns`也是

![1673319430184](https://user-images.githubusercontent.com/34130829/211451612-be5f1529-a8a3-431d-baa0-2faf17ea5ebb.png)

3.然后表单页面的内容没有任何改变 ,还是之前的那些字段

![1673319487901](https://user-images.githubusercontent.com/34130829/211451755-fc54f105-55ca-4aa2-98fe-d986d620d472.png)

## 最小可复现例子（必需）

[仓库地址](https://github.com/QJAutumn/Onchange-bug)

## 复现步骤

1. 克隆代码,然后执行`yao migrate && yao run scripts.demo.Data` 执行`yao start`
2. 访问`http://127.0.0.1:5099/admin/login/admin`
3. 账号:[xiang@iqka.com](mailto:xiang@iqka.com)  密码:A123456p+
4. 登录进去-->点击[表单]菜单-->修改住院天数字段触发onchange操作,如下图

![1673320322170](https://user-images.githubusercontent.com/34130829/211453530-182a14fa-c0d7-40dc-8c3d-3538715d0dac.png)

## Context

- **Yao Version( 0.10.3 )[下载地址](https://github.com/YaoApp/yao/suites/10189972221/artifacts/498706194)**:
- **Xgen Version( Build Info:time:2023-01-05T00:45:08+00:00|version:1.2.0)**:
- **Linux虚拟机**:

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/xgen/commit/71328a3d2c84470bec376089be5d7b6c500491bf

**Comment by QJAutumn** [comment]
> [YaoApp/xgen@71328a3](https://github.com/YaoApp/xgen/commit/71328a3d2c84470bec376089be5d7b6c500491bf)

有这样的一个情况:考虑一个编辑页面有两个【或者更多个】onChange的情况,两个onchange一个A 【渲染数据1,2,3】,一个B【渲染数据4,5,6】,
A事件把数据渲染上去了1,2,3,
B事件渲染4,5,6,但是B事件没有123的数据,返回setting的时候是没有123的,这样会导致123的数据被B事件给覆盖了

**Comment by MatrixAge** [comment]
复现仓库

**Comment by MatrixAge** [comment]
提供的`最小复现仓库`不满足复现条件：
![image](https://user-images.githubusercontent.com/25472851/211748272-bdd5de76-5cda-41a0-90bd-03f7c3952f79.png)

**Comment by QJAutumn** [comment]
已经修复

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/xgen/commit/8657ca5fffecec1eafbdc84b06ba54c4e7428b98

**Comment by QJAutumn** [comment]
好了,没问题了
