### ISSUE TITLE
无法在页面上进行低代码

### ISSUE THREAD

**Issue by liuyl1992** [YaoApp/yao#31]
无法在页面上进行低代码，现在必须通过把json描述在服务器放到指定目录，执行指令才可生成数据和接口，页面吗。
是否后续支持翔其他低代码平台一样，在页面进行数据模型的描述，就可生成接口和页面

**Comment by MatrixAge** [comment]
目标不一样，我们致力于提供工具，后面也会提供本地运行的可视化界面。
