### ISSUE TITLE
[Bug] 首页重定向问题

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#310]
## 最小可复现例子（必需）
仓库地址[github](https://github.com/QJAutumn/List-Bug)
克隆代码后 ,执行yao migrate && yao run scripts.demo.Data
访问http://127.0.0.1:5099/admin/login/user
多点击几次刷新按钮就会出现

线上:
1.访问user端[网页](https://zdyk-project.iqka.com/admin/login/user),然后点击左上角刷新按钮,多点击几次
2.访问admin端[网页](https://zdyk-project.iqka.com/admin/login/admin),然后切换到user端,然后点击左上角刷新按钮,多刷新几次

## 复现步骤
点击查看 [复现视频](https://release-bj-1252011659.cos.ap-beijing.myqcloud.com/bug/20230111_111415.mp4)

第一步: [访问用户端](https://zdyk-project.iqka.com/admin/login/user)

第二步 :点击右上角刷新按钮,多刷新几次,url会变成`https://zdyk-project.iqka.com/admin/login/admin`

第三步:当url后缀变成admin后,在地址栏上把url后缀改成user,没有效果,还是admin

## Context
浏览器google,windows
- **Yao Version( 0.10.3 )[下载地址](https://github.com/YaoApp/yao/suites/10189972221/artifacts/498706194)**:
- **Xgen Version( Build Info:time:2023-01-05T00:45:08+00:00|version:1.2.0)**:
- **Linux虚拟机**:

**Comment by MatrixAge** [comment]
复现仓库

**Comment by QJAutumn** [comment]
好的,添加了

**Comment by MatrixAge** [comment]
在xgen-dev-app和你提供的复现仓库中，均未复现，线上例子版本非最新版本：
![image](https://user-images.githubusercontent.com/25472851/211750183-ca5a18e2-27f4-4549-bf00-1c31e1f6dda5.png)

**Comment by QJAutumn** [comment]
【最新发现:**打开F12然后狂点击是不会出现这个问题的,关闭F12就会**】
使用这个仓库[地址](https://github.com/QJAutumn/List-Bug)
克隆代码后 ,执行yao migrate && yao run scripts.demo.Data && yao start
访问http://127.0.0.1:5099/admin/login/user
多点击几次【狂点击】刷新按钮就会出现,有的时候二维码还会变成白色的,空的
然后yao使用这个版本的[链接](https://github.com/YaoApp/yao/suites/10302362639/artifacts/506524717)
用xgen-dev-app他没有配置user端,点击不了的吧

**Comment by QJAutumn** [comment]
已经修复
