### ISSUE TITLE
docker 安装和启动 yao ，页面登录默认帐号后，跳转的页面一直白屏

### ISSUE THREAD

**Issue by blackdogcat** [YaoApp/yao#313]
## 发生了什么?
docker 安装和启动 yao  ，页面登录默认帐号后，跳转的页面一直白屏

## 相关截图（必需）
跳转到 /admin/x/Chart/dashboard 后，页面报错信息
![image](https://user-images.githubusercontent.com/16526343/212520660-9031d16e-f497-49ea-8033-94a036d60898.png)

## 最小可复现例子（必需）
部署问题，无代码执行例子。
## 复现步骤
**Docker 安装 yao**1.1.
根据以下文档操作
https://yaoapps.com/doc/%E4%BB%8B%E7%BB%8D/%E5%AE%89%E8%A3%85%E8%B0%83%E8%AF%95
执行 docker run -d --name yao-dev -v /root/data/yao:/data/app -p 5099:5099 yaoapp/yao:0.10.3-amd64-dev
当执行完 yao start 命令后，配置时使用默认数据库 sqlite
**帐号登录，应该能看到yao的工作台** 1. 2.
实际上页面上登录默认帐号，管理后台默认用户名: xiang@iqka.com， 密码: A123456p+
跳转到 /admin/x/Chart/dashboard 后，页面一直是白屏的情况。

## Context
- **Yao Version**
![image](https://user-images.githubusercontent.com/16526343/212507784-7bbe5d3b-8d0d-4b8c-a528-dae1e92e4877.png)
- **Platform**:
阿里云 centos7
```
[root@iz2ze7546aqz9f64rpm34wz ~]# uname -a
Linux iz2ze7546aqz9f64rpm34wz 3.10.0-693.2.2.el7.x86_64 #1 SMP Tue Sep 12 22:26:13 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
```
- **Docker Version**:
```
Client:
 Version:         1.13.1
 API version:     1.26
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64

Server:
 Version:         1.13.1
 API version:     1.26 (minimum version 1.12)
 Package version: docker-1.13.1-209.git7d71120.el7.centos.x86_64
 Go version:      go1.10.3
 Git commit:      7d71120/1.13.1
 Built:           Wed Mar  2 15:25:43 2022
 OS/Arch:         linux/amd64
 Experimental:    false
```

**Comment by trheyi** [comment]
使用 v0.10.2 试试。

```bash
docker run -d --name yao-dev  -p 5099:5099 yaoapp/yao:0.10.2-amd64-dev
```

进入容器

```bash
docker exec -it yao-dev /bin/bash
```

在容器内运行

```bash
yao start
```
根据提示安装
http://127.0.0.1:5099



v0.10.3 尚未正式发布，还在内测中，菜单部分向下兼容尚未完成。 
v0.10.3 应用参考 https://github.com/YaoApp/xgen-dev-app

**Comment by blackdogcat** [comment]
感谢 yao:0.10.2-amd64-dev 这个版本可以部署成功，我先用这个版本。v0.10.3 先不看了。
