### ISSUE TITLE
教程文档里的 处理器 章节 很多无法查看，求更新

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#32]
<img width="1701" alt="image" src="https://user-images.githubusercontent.com/49874458/157412395-24a29ac2-65bc-4c13-b70d-5102331a93b0.png">

大家如果也想学习使用这个项目就在下面留言吧，博主说这个项目学习使用的人多了，他们就会积极更新的

**Comment by ahlblzk** [comment]
https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/c.%E4%B8%BA%E4%BB%80%E4%B9%88%E9%80%89%E6%8B%A9Yao
这里有个错别字 
<img width="979" alt="image" src="https://user-images.githubusercontent.com/7858842/157696211-c8adfd12-8f80-4a2a-9962-794df73f43e0.png">

**Comment by mapan1908** [comment]
求同，很多无法查看

**Comment by zhoucat** [comment]
同求

**Comment by mapan1908** [comment]
增删改查的文档都不全？是不是太坑了？

**Comment by fly0512** [comment]
按照文档流出逐步操作，到新增数据就玩不下去了，文档都是500，上面提到的内部使用文档，也没有内容啊？

**Comment by trheyi** [comment]
@fly0512  多点两下鼠标
https://github.com/YaoApp/docs-yao/tree/main/model/process
https://github.com/YaoApp/docs-yao/tree/main/table/apis

**Comment by fly0512** [comment]
参考演示代码跑通了增删改查,现在找批量选择和批量删除怎么用的,演示代码好像也没有用到?

**Comment by cebrains** [comment]
错字问题挺严重的，不只是文档，源码取名也有很多，比如fileds，decription等
