### ISSUE TITLE
[Bug] 使用Onchange联动问题

### ISSUE THREAD

**Issue by QJAutumn** [YaoApp/yao#321]
## 使用Onchange做一个二级联动功能,返回的setting的Select组件似乎没有起到作用,之前有个版本是好的,然后这个版本又不能渲染了
![1674200319857](https://user-images.githubusercontent.com/34130829/213642291-0c2cdb38-b085-4d76-900b-a2c6cb067b14.png)

## 相关截图（必需）
1.我的名称有一个Onchange事件,别名根据名称字段返回的setting来渲染成对应的下拉列表
2.然后setting的` setting["fields"]["form"]["别名"]["edit"]["props"]["options"]`已经赋值为对应的下拉了,但是点击别名的时候,还是原来的下拉列表,
## 最小可复现例子（必需）
[仓库地址](https://github.com/YaoApp/bug-check)

## 复现步骤

1.克隆仓库代码 [仓库地址](https://github.com/YaoApp/bug-check)
2.执行yao migrate && yao run scripts.demo.Data
3.访问`http://127.0.0.1:5099/admin/login/admin`
4.线上地址https://bug-check.iqka.com/admin/login/admin
5.账号:[xiang@iqka.com](mailto:xiang@iqka.com)

密码:A123456p+
点击这个菜单:
![1674201009817](https://user-images.githubusercontent.com/34130829/213644051-b0fb050f-9118-4d92-9232-758fb8e5b7e7.png)

## Context

- **Yao Version( 0.10.3 )**: [下载地址:](https://github.com/YaoApp/yao/suites/10478608815/artifacts/519240227)
- **Xgen Version( Build Info )**: Built Info" content="time:2023-01-20T01:52:18+00:00|version:1.4.0
- **Platform**:Linux

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/215239874-caafb2b8-63ba-45e4-99e2-9fdb17c7d592.png)

无法复现

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/xgen-dev-app

重新打包一份Yao，部署这个的配置到线上看看会不会出现

**Comment by QJAutumn** [comment]
我试了一下你这样写是可以的,但是你只要把`scripts/event.js`的OnChange方法改成我这个,他就不行了
```
function OnChange(info) {
  console.log(info);

  let data = { attack: 10 }; // 更新消费金额数据, 消费金额
  let setting = Process("yao.form.Setting", "hero"); // 根据新数值生成配置信息
   setting["fields"]["form"]["位置"]["edit"]["props"]["options"]= [
    {
      label: "上单",
      value: "上单",
    },
    {
      label: "中单",
      value: "中单",
    },
    {
      label: "打野",
      value: "打野",
    },
  ];
  return {
    data: data,
    setting: setting,
  };
}
```

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/215253170-7d910574-6e56-40c3-8a60-f36e320b2962.png)

看一下处理器返回的结构和实际接口返回接口的差异。

我复制接口返回结果的setting是正常的，说明处理器返回的setting可能有问题。

**Comment by MatrixAge** [comment]
拉取最新的xgen，应该没问题了，这个是Select的问题，不是onChange。

**Comment by QJAutumn** [comment]
好的

**Comment by QJAutumn** [comment]
没问题了

**Comment by QJAutumn** [comment]
【问题又出现了】:这次是【Input】输入框不能渲染数据
### 相关截图
名称使用Onchange,返回的的数据为,但是列表没有渲染上去,现在变成Input输入框不能渲染了
```
{
    "attack": 400,
    "difficulty": 6700,
    "name": "寒冰"
}
```
![1675646927109](https://user-images.githubusercontent.com/34130829/216861503-317ef1b0-1020-40ec-bc27-a4fe74b93f8b.png)

### 最小可复现例子（必需）
[仓库](https://github.com/YaoApp/bug-check)

### 复现步骤
1.克隆仓库代码 [仓库地址](https://github.com/YaoApp/bug-check)
2.执行yao migrate && yao run scripts.demo.Data
3.访问http://127.0.0.1:5099/admin/login/admin
4.线上地址https://bug-check.iqka.com/admin/login/admin
5.账号:[xiang@iqka.com](mailto:xiang@iqka.com)

密码:A123456p+
点击如图菜单->点击名称下拉j ,就能看到效果
![1675647156551](https://user-images.githubusercontent.com/34130829/216861930-48e1b218-2d11-4d09-bfb8-0d89084868ac.png)

### Context
Yao Version( 0.10.3 ): [下载地址:](https://github.com/YaoApp/yao/suites/10758316822/artifacts/540118029)
Xgen Version( Build Info ): "Built Info" content="time:2023-02-03T10:00:02+00:00|version:1.4.0"
Platform:Linux
