### ISSUE TITLE
[Feature Request] 兼容移动端

### ISSUE THREAD

**Issue by YuzeTT** [YaoApp/yao#323]
## 需求背景

有手机录入数据的需求

## 提案

参考
![image](https://user-images.githubusercontent.com/61106448/215404293-25b0bd46-af3e-46b3-ad07-37f269f9b7a5.png)

**Comment by MatrixAge** [comment]
这块建议使用小程序根据YAO提供的服务自行定制，移动端投产比太低，花时间在这上面不划算。

**Comment by chmis8000** [comment]
> 这块建议使用小程序根据YAO提供的服务自行定制，移动端投产比太低，花时间在这上面不划算。

企业微信/钉钉内嵌H5, 也是有移动端的录入需求,不管是H5/小程序, 至少有一个移动端的解决方案吧
