### ISSUE TITLE
[Bug] Watching热更新无效

### ISSUE THREAD

**Issue by rainame** [YaoApp/yao#329]
## 发生了什么?

在docker中初次使用`yao start`启动项目之后，修改`tables\pet.tab.json`文件，更改显示的`columns`，之后刷新页面，还是原来的的布局，热更新没生效，必须手工重启后文件更改才会生效。另外终端控制台无任何输出，无论是否加上`--debug`参数。

## 最小可复现例子（必需）

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

`tables\pet.tab.json`文件修改前：
```json
{
  "name": "::Pet Admin Bind Model",
  "action": {
    "bind": { "model": "pet", "option": { "form": "pet" } }
  }
}
```

`tables\pet.tab.json`文件修改后：
```json
{
  "name": "::Pet Admin Bind Model",
  "action": {
    "bind": { "model": "pet", "option": { "form": "pet" } }
  },
  "layout": {
    "header": { "preset": {} },
    "table": {
      "columns": [
        { "name": "昵称", "width": 200 },
        { "name": "类型", "width": 200 }
      ]
    }
  }
}
```

## Context

- **Yao Version( Detail Version )**: 0.10.2-e0c2ca7f4bd3-2022-11-21T01:42:30+0000
- **Xgen Version( Build Info )**:
- **Platform**: Windows 10

**Comment by WGinit** [comment]
参考：https://github.com/YaoApp/yao/issues/66

**Comment by jackbaihaochen** [comment]
使用的是Mac，docker启动，我这里也是，API文件保存后无法热更新
