### ISSUE TITLE
创建数据模型-数据查询-按主键查询数据：yao run models.pet.Find 1  报错

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#33]
<img width="693" alt="image" src="https://user-images.githubusercontent.com/49874458/157413775-283c44fd-3d1d-4819-9939-3ac7d5b70582.png">
Find 后面跟一个数会报错，跟2个数才会正常运行，且只使用第一个数字，第二个数字无用

**Comment by trheyi** [comment]
感谢反馈。

例如：
yao run models.product.find 1 '::{"withs":{"manu":{}}, "select":["id", "name"]}'

第二个参数是查询条件，稍晚些更新 处理器文档。
