### ISSUE TITLE
cannot subscribe to newsletter on yaoapps.com

### ISSUE THREAD

**Issue by gregoriopellegrino** [YaoApp/yao#34]
Hi,
I'm trying to subscribe to the newsletter from [homepage](https://yaoapps.com/en-US), but I get "Email format validation error!"

Gregorio

**Comment by gregoriopellegrino** [comment]
My email is in format firstname.lastname@domain.com

**Comment by MatrixAge** [comment]
> My email is in format [firstname.lastname@domain.com](mailto:firstname.lastname@domain.com)

Thanks feedback,i will fix it.

**Comment by MatrixAge** [comment]
@gregoriopellegrino 

I have been fixed it.
