### ISSUE TITLE
希望早日实现 JSON 的操作全部可视化 奥里给

### ISSUE THREAD

**Issue by liuyl1992** [YaoApp/yao#36]
[未来](https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/c.%E4%B8%BA%E4%BB%80%E4%B9%88%E9%80%89%E6%8B%A9Yao#%E6%9C%AA%E6%9D%A5)
我们会在未来的日子里推出可视化操作的服务，将对 JSON 的操作全部可视化，这样能进一步降低开发门槛，让小白用户看着开发文档也能轻松开发企业级后台应用。我们也在考虑对一些核心模块进行重构，以此来让使用 JSON 的开发者和使用可视化界面的开发者拥有同等的便利。

**Comment by liuyl1992** [comment]
json的操作可视化如果也依靠现有能力配置出来实现自举那就更好了，鸡生蛋，蛋生鸡

**Comment by trheyi** [comment]
感谢建议，这主意很棒 👍🏻
