### ISSUE TITLE
[Bug] xgen 图片地址带有 url 参数无法正常显示

### ISSUE THREAD

**Issue by wwsheng009** [YaoApp/yao#361]
## 发生了什么?

图片地址带有 url 参数无法正常显示

## 最小可复现例子（必需）

https://github.com/wwsheng009/xgen-pic-display-bug.git

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

```sh
git clone https://github.com/wwsheng009/xgen-pic-display-bug.git

cd xgen-pic-display-bug

yao start

# User Name
xiang@iqka.com
# Password
A123456p+
```

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2. 

图片url带有参数的应该也能正常显示

## Context

- **Yao Version( Detail Version )**: yao-0.10.3-pre
- **Xgen Version( Build Info )**:
- **Platform**: linux

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/xgen/commit/bb39771e943d72b83459559f6dcc9a6033c35368

**Comment by wwsheng009** [comment]
thanks,test passed.
