### ISSUE TITLE
[Bug] 0.10.3-pre 与 0.10.3-dev 中 jsapi 中调用 studio 脚本存在不一致的行为

### ISSUE THREAD

**Issue by wwsheng009** [YaoApp/yao#364]
## 发生了什么?

0.10.3-DEV studio 无法在 jsapi 中正常运行

## 最小可复现例子（必需）

https://github.com/wwsheng009/studio-jsapi-not-working

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤
```sh
git clone https://github.com/wwsheng009/studio-jsapi-not-working.git

cd studio-jsapi-not-working && mkdir db && yao migrate --reset
```
0.10.3-pre 与 0.10.3-dev 中 jsapi 中调用 studio 脚本存在不一致的行为。

```sh
// yao-dev studio run echo.hello
function hello() {
  return "你好";
}

// yao-pre studio run echo.World => ok
// yao-dev studio run echo.World => error
function World() {
  //0.10.3-pre 不需要增加studio也能识别
  return Studio("echo.hello");
}

// yao-dev studio run echo.World2   =>ok
// yao-pre studio run echo.World2   =>error
function World2() {
  //0.10.3-dev 需要增加studio前缀才能识别
  return Studio("studio.echo.hello");
}
```

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

在0.10.3-dev版本中应该与之前的版本一样，在jsapi中运行studio脚本不需要增加前缀studio。

## Context

- **Yao Version( Detail Version )**:0.10.3-dev(main)
- **Xgen Version( Build Info )**:latest
- **Platform**:linux

**Comment by MatrixAge** [comment]
@trheyi

**Comment by trheyi** [comment]
fixed
https://github.com/YaoApp/gou/commit/d147c7312a507a6e1b50aeea0ef2367846a686bb
https://github.com/YaoApp/yao/actions/runs/4992472043
