### ISSUE TITLE
最新docker 版 v0.9.1 环境变量不生效

### ISSUE THREAD

**Issue by liuyl1992** [YaoApp/yao#39]
最新docker 版 v0.9.1 环境变量不生效，数据库驱动设置mysql 后，用yao命令查看变量是生效了，但是运行日志显示完全没读取环境变量

**Comment by trheyi** [comment]
具体的错误日志是信息是？ 

```bash
cd /data/app
yao inspect
```

**Comment by liuyl1992** [comment]
> 具体的错误日志是信息是？
> 
> ```shell
> cd /data/app
> yao inspect
> ```
没有任何错
![企业微信截图_16469690199752](https://user-images.githubusercontent.com/16396828/157796489-f2c4a35c-de39-4993-8cd0-84ddcfe08612.png)

**Comment by trheyi** [comment]
driver 显示是 `sqlite3`  `cat  .env` 的配置是？

**Comment by trheyi** [comment]
如果当前目录下的 .env 是 MySQL ，yao inspect 的结果应该一致，可以检查一下环境变量名称是否正确。

**Comment by liuyl1992** [comment]
> 如果当前目录下的 .env 是 MySQL ，yao inspect 的结果应该一致，可以检查一下环境变量名称是否正确。
名称一定没问题的，但yao就是始终默认production
![image](https://user-images.githubusercontent.com/16396828/159207933-c90cfb66-b7dd-40a9-9425-f06066330c93.png)

**Comment by 41668895** [comment]
![image](https://user-images.githubusercontent.com/101466847/159213889-22785d1b-726f-4bf0-bd44-15255c3899ef.png)
![image](https://user-images.githubusercontent.com/101466847/159214066-a3954f65-fc8c-4169-a0e0-9d43ed39f49b.png)

**Comment by liuyl1992** [comment]
那文档说的要优化，有企业，都以为是linux的环境变量
