### ISSUE TITLE
基础特性-编写接口-接口调试:curl 'http://127.0.0.1:5099/xiang/api/pet/search?where.name.match=Cookie&page=1&pagesize=1' 会因为登录鉴权问题访问不到结果。

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#40]
<img width="1370" alt="image" src="https://user-images.githubusercontent.com/49874458/157582558-a18f7fdf-3d7c-481b-83a9-89ba0287496f.png">

登录鉴权可以对一些接口关闭么？

或者提供另一种方式，先使用用户名密码访问登录接口获取token，然后拿token放在请求头里，去访问自定义接口

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/157623657-e783f7b1-c732-49d8-8bdf-2536ab311fe8.png)

这样设置，用来测试接口。

This setting is used to test api.

**Comment by liushuainice** [comment]
<img width="1564" alt="image" src="https://user-images.githubusercontent.com/49874458/157627952-05e48423-0354-4a8c-9be6-377944b1e9e5.png">

还是测试不通。另外，”编写接口“是否有字段说明讲解的章节文档？像 guard ，in，out，query等一些字段不明白具体含义和使用方法

**Comment by MatrixAge** [comment]
@trheyi

**Comment by trheyi** [comment]
@liushuainice  路由地址为 `/api/xxxx`   文档 https://yaoapps.com/doc/f.%E5%8F%82%E8%80%83%E6%89%8B%E5%86%8C/c.%E6%8E%A5%E5%8F%A3

**Comment by liushuainice** [comment]
测试成功，感谢

**Comment by YahuiAn** [comment]
[接口描述](https://yaoapps.com/doc/b.%E5%9F%BA%E7%A1%80%E7%89%B9%E6%80%A7/b.%E7%BC%96%E5%86%99%E6%8E%A5%E5%8F%A3#%E6%8E%A5%E5%8F%A3%E6%8F%8F%E8%BF%B0) 中的 ``guard``:"bearer-jwt" 不生效

![image](https://user-images.githubusercontent.com/39142491/180691842-7d9a7261-ad68-41ac-9d57-d9db7ec6369f.png)

![image](https://user-images.githubusercontent.com/39142491/180692085-15ebb023-8351-465e-8860-c820126634a2.png)



指定了 bearer-jwt 鉴权，但是 curl 可以直接访问呢？

```
curl http://127.0.0.1:5099/api/pet/search
```

![image](https://user-images.githubusercontent.com/39142491/180691999-1f35a3f7-9951-4a6d-82aa-41204496eb1b.png)

**Comment by MatrixAge** [comment]
测试时 guard: "-" 即可
