### ISSUE TITLE
数据模型关联-"指定关联模型的选取字段"和"按关联模型的字段查询条件" 查询条件均未生效

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#41]
<img width="1630" alt="image" src="https://user-images.githubusercontent.com/49874458/157605760-2060f6a6-7384-42b3-ada0-c72cea0b262d.png">

<img width="1208" alt="image" src="https://user-images.githubusercontent.com/49874458/157605949-1e15219f-6c2c-40e0-875b-afc73991cfad.png">

这块的条件我尝试了多种形式，但都无效，无法对"relations"对象进行 select 和where查询

**Comment by trheyi** [comment]
文档稍后修正. 
```bash
yao run models.user.Find 1 '::{"withs":{ "supplier": { "query":{"select":["name"] }} }}'
```

**Comment by liushuainice** [comment]
测试指令没有问题

**Comment by trheyi** [comment]
@liushuainice   嵌套查询 条件需要加在query里 ，文档相对滞后，稍晚些更新文档，并增加更多关联查询例子。 
所以你的问题解决了吗？

**Comment by liushuainice** [comment]
@trheyi 解决
