### ISSUE TITLE
文档-“接口”章节 与 “编写接口”章节，有字段不一致 

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#43]
<img width="1172" alt="image" src="https://user-images.githubusercontent.com/49874458/157669696-993558ce-00e9-47d1-a08f-5ebc57ddeb89.png">
<img width="1355" alt="image" src="https://user-images.githubusercontent.com/49874458/157669910-6667e3e9-48d5-4441-ab2f-46fb57e081e6.png">

 “编写接口”章节的例子有 query 字段，“接口”章节 字段里没有

**Comment by trheyi** [comment]
文档相对滞后，还有不少疏漏，感谢反馈，同时也欢迎PR /:heart 
 https://github.com/YaoApp/website-doc-zh-CN

**Comment by liushuainice** [comment]
这个项目我感觉非常好，真心希望以后我的工作可以用到这个项目，我会持续探索测试，个人水平有限，PR我不太会，有问题我会继续发issues的 ：）

**Comment by trheyi** [comment]
感谢支持，也欢迎多发 issues :)
