### ISSUE TITLE
[Bug] yao关闭后，好像ext目录下的plugin没有同时关闭

### ISSUE THREAD

**Issue by helperAI** [YaoApp/yao#433]
如题
## 发生了什么?
运行knowledge项目时，能够启动成功，但是退出后似乎plugin的库没有关闭。是最近2天git clone的代码。

<img width="805" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/a9a6eb1f-c49d-401f-844f-d04529020a2f">

## 最小可复现例子（必需）

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Yao Version( Detail Version )**:
- **Xgen Version( Build Info )**:
- **Platform**:

**Comment by trheyi** [comment]
未复现，yao 退出的方式是？

**Comment by trheyi** [comment]
无法复现
