### ISSUE TITLE
[Bug] example/neo项目登录成功后刚刚看到菜单，马上又返回到登录页面，提示：not allowed，但是其实token已经成功生成

### ISSUE THREAD

**Issue by helperAI** [YaoApp/yao#434]
## 发生了什么?
example/neo项目登录成功后刚刚看到菜单，马上又返回到登录页面，提示：not allowed，

<img width="1169" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/03101d9f-d9f7-427a-ac08-68b4668d0cf8">

但是其实token已经成功生成，因为我直接用api加上token在浏览器地址栏访问可以成功返回数据：
/neo/commands?token=Bearer%20eyJhbGciOiJIUzI1NiIsInR5cCI6Ikp.......
下面是返回数据：
<img width="1431" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/51605a1d-05cc-429f-905b-ebe434ce6b52">
奇怪的是console没有任何错误：
<img width="468" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/a44346a8-9536-49e8-8339-112aeabae159">

对了，mysql数据库初始化之后只有如下几个表：

<img width="332" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/2885d664-79c6-4e52-a77d-91e74c2a6c34">

运行

yao run flows.app.menu的返回数据如下，菜单应该是正常的吧？
--------------------------------------
flows.app.menu Response
--------------------------------------
{
    "items": [
        {
            "badge": 6,
            "blocks": 0,
            "children": [
                {
                    "blocks": 0,
                    "icon": "icon-activity",
                    "name": "看板",
                    "path": "/x/Dashboard/kanban",
                    "visible_menu": 1
                },
                {
                    "blocks": 0,
                    "icon": "icon-activity",
                    "name": "图表",
                    "path": "/x/Chart/pet",
                    "visible_menu": 1
                },
                {
                    "blocks": 0,
                    "name": "表格",
                    "path": "/x/Table/demo.pet",
                    "visible_menu": 1
                },
                {
                    "blocks": 0,
                    "name": "表单(编辑)",
                    "path": "/x/Form/demo.pet/1/edit",
                    "visible_menu": 1
                },
                {
                    "name": "表单(查看)",
                    "path": "/x/Form/demo.pet/1/view",
                    "visible_menu": 1
                },
                {
                    "name": "自定义页面",
                    "path": "/iframe?src=/demo/pet.html",
                    "visible_menu": 1
                }
            ],
            "icon": "icon-book",
            "name": "演示",
            "path": "/x/Dashboard/kanban",
            "visible_menu": 0
        }
    ],
    "setting": [
        {
            "blocks": 0,
            "icon": "icon-user",
            "name": "管理员",
            "path": "/x/Table/admin.user",
            "visible_menu": 0
        },
        {
            "children": [
                {
                    "badge": 24,
                    "name": "设置项演示",
                    "path": "/x/Form/demo.pet/1/edit"
                },
                {
                    "name": "系统设置",
                    "path": "/setting"
                }
            ],
            "dot": true,
            "icon": "icon-settings",
            "id": 999999,
            "name": "设置",
            "path": "/x/Form/demo.pet/1/edit"
        }
    ]
}

## 最小可复现例子（必需）

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

<img width="401" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/435e1e6c-c9d7-489a-ac5b-c952c5c91afe">

**Comment by trheyi** [comment]
跨域请求导致 ,  在  neo.yml allows 里添加 host地址

allows:
  - "http://127.0.0.1:8000"
  - "http://127.0.0.1:5099"
  - "http://localhost:5099"
  - "http://localhost:8000"
  - "http://172.17.0.1:5099"
  - "http://172.17.0.1:5077"
