### ISSUE TITLE
[Bug] yao start 后配置数据库时提示 配置失败，失败原因:mkdir xxx/root/yao/tests/logs: not a directory

### ISSUE THREAD

**Issue by xiaochaom** [YaoApp/yao#435]
## 我在ubuntu服务器上执行了 curl -fsSL https://website.yaoapps.com/install.sh | bash  后,在空目录执行 yao start,提示失败.失败原因:mkdir xxx/root/yao/tests/logs: not a directory

因为该目录已自动生成logs文件,所以logs目录不可被创建导致报错

## 相关截图（必需）
![image](https://github.com/YaoApp/yao/assets/21215047/13676107-efca-4896-9260-dc68616f55c2)

## 最小可复现例子（必需）
1. 执行 curl -fsSL https://website.yaoapps.com/install.sh | bash
2. 空目录执行 yao start
3. 使用 mysql 方式配置数据库

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Yao Version( Detail Version )**:
- **Xgen Version( Build Info )**:
- **Platform**:

**Comment by trheyi** [comment]
在空目录，运行 yao start
