### ISSUE TITLE
[Bug] yao-knowledge的demo，运行desktop的上传pdf文件，出错

### ISSUE THREAD

**Issue by helperAI** [YaoApp/yao#436]
mac上运行desktop，然后上传pdf文件到右上角的小按钮，mac的console显示：

<img width="461" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/72d225e2-ddcd-415a-9054-b6f70080ac38">

查看yao的application.log文件最后几行也是属于正常的：
time="2023-06-07T13:21:50Z" level=info msg="[Watch] Watching: /www/wwwroot/yao/yao-knowledge/web/src/components"
time="2023-06-07T13:21:50Z" level=info msg="[Watch] Watching: /www/wwwroot/yao/yao-knowledge/web/src/routes"
time="2023-06-07T13:21:50Z" level=info msg="[Watch] Watching: /www/wwwroot/yao/yao-knowledge/yao-exts"

但是在yao的console中显示如下错误信息，此类错误信息完全看不出原因。

[README.txt](https://github.com/YaoApp/yao/files/11677683/README.txt)
 我把编译的是linux环境的pdf.so

yao的环境：
<img width="387" alt="image" src="https://github.com/YaoApp/yao/assets/75373309/63f49541-ad1e-43ac-8a79-2b5f892eb45e">

**Comment by trheyi** [comment]
信息不完整, 提交到 https://github.com/YaoApp/yao-knowledge 。
从你给的截图上看像是 客户端无法跟服务端通信。 

说明清楚以下信息: 

    1.  客户端的配置信息，启动方式等。
    2.  提供完整的应用日志  tail -n 500
