### ISSUE TITLE
[Bug] flow和task使用中的问题

### ISSUE THREAD

**Issue by napfy** [YaoApp/yao#437]
相关代码已上传至
https://gitee.com/napfy/yao0608.git

遇到两个可能是bug的问题：
1. 文件flows/sms/utest.flow.yao中第一个node（名为"user"）的返回值为null，而切换到js中执行则可以正确返回数据。
2. 使用task功能调用插件无法正确执行，但单独调用插件可以执行。且该调用方式及相关代码结构是从另一个运行良好的项目上拷过来的。

#### 架构
- plugin目录 一个测试用的redis插件源码
- yao0608目录是放yao相关配置文件的目录，还缺少一个.env

#### 使用说明

1.  需要准备login和student表的数据，login中的id与student中的uid有关联
2.  测试时对scripts/test.js文件中的代码，有两个相同的函数，
3.  插件使用.env中YAO_SESSOION_HOST和YAO_SESSION_PORT的设置，要求YAO_SESSION_STORE="redis"
4.  单独测试插件功能可以使用 yao run plugins.rmem.set name joe 和 yao run plugins.rmem.get name

**Comment by trheyi** [comment]
问题已修复先手动下载更新 Yao （下载替换容器中的 yao 命令即可)  ， 测试没问题后再更新镜像。
下载地址:  https://github.com/YaoApp/yao/actions/runs/5213441279 



1. 第一个问题,  之前 dot 算法有一个 256 个数组长度限制，所以返回数据超过 256 时会返回 null， 已经去掉了个限制。
   https://github.com/YaoApp/kun/commit/c6255211b76d9d0662ac0e7c7ffa000d2f1a7359

2. 新版中, 只有 yao start 启动 task 服务。yao run  没有启动 task 服务，已经增加上了。
    使用时注意: 需要自己添加等待任务完成逻辑。  
    之后有计划重构 task 服务，届时会增加等待任务完成后退出选项。


```jsonc
{
  "label": "发送合格证下载提醒短信",
  "version": "1.0.0",
  "description": "",
  "nodes": [
    {
      "name": "user",
      "process": "models.student.Get",
      "args": [
        {
          "select": ["uid", "name"],
          "wheres": [{ "column": "checked", "value": "已过审" }],
          "withs": { "login": {} },
          "limit": 5000
        }
      ]
    },
    {
      "name": "filter",
      "process": "scripts.test.taskplugin",
      "args": ["{{$res.user}}"]
    },
    {
      "name": "WaitComplete",
      "process": "scripts.cachetask.WaitComplete"
    }
  ],
  "output": "{{$res.filter}}"
}

```
  
```javascript

function WaitComplete() {
  let done = false;
  while (!done) {
    console.log(`WaitComplete: 5s`);
    time.Sleep(5000);
    done = true;
  }

  console.log("WaitComplete: done");
}

```

3. 插件退出是因为传入了空值 

```javascript

function Send(id, message) {
  //  console.log("^^^^^^^^")
  console.log(message);
  // rslt = message["mobiles"] + "|" + message["tpl"] + "|" + message["args"]
  const rslt = Process(
    "plugins.rmem.set",
    message["key"],
    message["val"] || "empty"
  );
  // console.log(rslt);
  return "ok";
}

```
