### ISSUE TITLE
[Bug] Table组件: 批量勾选不显示

### ISSUE THREAD

**Issue by WGinit** [YaoApp/yao#447]
## 发生了什么?
在.tab.yao文件中设置table中的layout.header.preset.batch后，页面中没有显示勾选框
```jsonc
{
  ...
  "header": {
      "preset": {
          "batch": {
              "columns": [
                  { "name": "名称", "width": 12 }
              ],
              "deletable": true
          }
      }
  },
  "table": {
        "props": {},
        "columns": [
            {
                "width": 100,
                "name": "名称"
            },
            ...
         ]
   }
   ...
}
```

## 相关截图（必需）
![img](https://i.imgur.com/BBXsJ25.png)

## 最小可复现例子（必需）

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Yao Version( Detail Version )**: 0.10.3
- **Xgen Version( Build Info )**: 1.4.1
- **Platform**:  Windows 11

**Comment by MatrixAge** [comment]
给个复现仓库看看。

**Comment by WGinit** [comment]
@MatrixAge https://github.com/WGinit/Demo/tree/master/yao-table
