### ISSUE TITLE
[Bug] demo app “Cannot read properties of undefined (reading 'pagination')”

### ISSUE THREAD

**Issue by longyn** [YaoApp/yao#449]
## 发生了什么?

Cannot read properties of undefined (reading 'pagination')

## 相关截图（必需）

Microsoft Edge
Version 114.0.1823.67 (Official build) (64-bit)

![image](https://github.com/YaoApp/yao/assets/5205838/c783fb32-a50e-4134-a8be-db0f5fea7c5d)

## 最小可复现例子（必需）

- yao: 0.10.3
- yao start
- 使用最新Edge打开， 出现错误

console输出
![Uploading image.png…]()

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

**Expected behavior** 1. 2.

## Context

- **Yao Version( Detail Version )**:
- **Xgen Version( Build Info )**:
- **Platform**:

**Comment by yxl** [comment]
我是因为系统语言不是中文导致的，参照下面的把浏览器语言改为中文就解决了。
https://blog.csdn.net/qq_41952224/article/details/132622915

**Comment by HaveF** [comment]
> 我是因为系统语言不是中文导致的，参照下面的把浏览器语言改为中文就解决了。 https://blog.csdn.net/qq_41952224/article/details/132622915

的确是这个问题。

**Comment by chennqqi** [comment]
这个问题官方什么时候修复一下？
