### ISSUE TITLE
希望 文档"章节"的说明里可以补充参数的测试指令

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#46]
以文档中最后的 “完整示例”为例，里面涉及到的参数格式有 $query :params $param $payload，请问这些形式的参数，都要如何填写请求参数。希望可以在“b变量”表格后面补充一列，举例一下这些形式的参数都是如何传递的
<img width="1489" alt="image" src="https://user-images.githubusercontent.com/49874458/157871785-4225b928-5f64-46c8-b49b-4fc0745509b0.png">

**Comment by trheyi** [comment]
好主意，0.9.2 发布完毕后在完善文档时加入。
