### ISSUE TITLE
中间件，如何自定义实现？

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#49]
<img width="1127" alt="image" src="https://user-images.githubusercontent.com/49874458/158020066-8ed09171-f8ff-4775-a700-52827d4bdb0a.png">
文档的 接口 章节里 有 guard 引用中间件的字段，目前通过文档只看到了 "guard": "bearer-jwt" 和"guard": "-"这两种，那中间件如何开发配置？这一章节的文档有么？

**Comment by trheyi** [comment]
有计划支持将 guard 与 处理器关联，实现自定义中间件。
