### ISSUE TITLE
请问以 json 作为 DSL，对服务端和客户端的 debug 是否友好？

### ISSUE THREAD

**Issue by zysam** [YaoApp/yao#52]
感谢作者提供这样的框架。
试运行 demo crm 后，发现：
1. 数据库兼容问题： demo 的数据驱动是 mysql ，改为 sqlite 后，发现兼容问题，修改下也可以跑起来。
2. debug 问题：json 对 debug 中不友好，不能 debug 出具体位置，靠经验猜。

想法：json 作为 DSL 使用，如果运行前没有格式和 DSL 关键字检测和运行时没有详细的报错，会不会给 debug 带来极大的困难？
请问作者在实际项目中，是怎么处理以上问题的？

**Comment by trheyi** [comment]
可以将 `debug` 参数设置为 true , 在控制台会打印解析后的 SQL。 另 DSL 还有一些简写的语法糖，文档相对滞后，晚些一起更新。

```json
 {
      "name": "查询单品库存",
      "engine": "xiang",
      "query": {
        "debug": true,
        "select": [":COUNT(id) as stock", "sku_id", "sku_sn"],
        "from": "$record",
        "wheres": [
          { ":plan_id": "计划ID", "=": "?:$in.0" },
          { ":sku_id": "单品ID", "=": "?:$in.1" },
          { ":status": "状态", "in": ["生效", "归档"] },
          { ":type": "类型", "=": "入库" }
        ],
        "first": 1
      }
    }
```

**Comment by trheyi** [comment]
一些常见写法可以参考单元测试的例子 https://github.com/YaoApp/gou/tree/main/query/assets

**Comment by zysam** [comment]
> 可以将 `debug` 参数设置为 true , 在控制台会打印解析后的 SQL。 另 DSL 还有一些简写的语法糖，文档相对滞后，晚些一起更新。
> 
> ```json
>  {
>       "name": "查询单品库存",
>       "engine": "xiang",
>       "query": {
>         "debug": true,
>         "select": [":COUNT(id) as stock", "sku_id", "sku_sn"],
>         "from": "$record",
>         "wheres": [
>           { ":plan_id": "计划ID", "=": "?:$in.0" },
>           { ":sku_id": "单品ID", "=": "?:$in.1" },
>           { ":status": "状态", "in": ["生效", "归档"] },
>           { ":type": "类型", "=": "入库" }
>         ],
>         "first": 1
>       }
>     }
> ```

谢谢
