### ISSUE TITLE
功能疑问：Webhook 通知 以及 API验证

### ISSUE THREAD

**Issue by maacck** [YaoApp/yao#53]
详细阅读了一下文档，但是目前有一些疑问不知道我理解的是否正确。

1. 目前没有看到支持API接口的验证，这个是否需要自行放到 Process里面去做？
2. 如上，假如当数据被修改时发送webhook通知，这个是否也是需要自行放到 Flows里面进行操作

**Comment by trheyi** [comment]
是的，逻辑简单可以使用数据流实现，逻辑复杂可以使用 JavaScript 脚本实现。参考文档 https://yaoapps.com/doc/c.%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7/d.%E4%BD%BF%E7%94%A8JS%E7%BC%96%E5%86%99%E5%A4%84%E7%90%86%E5%99%A8
