### ISSUE TITLE
编写第三方插件-这个插件都有什么要求？

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#56]
1，是否只可以用go语音编写？
2，对插件的格式和使用方法都有什么要求？是否要求必须为 .os后缀？
3，咱们是否可以建一个第三方插件库？由大家一起来提供好用可靠的插件？

**Comment by 41668895** [comment]
![image](https://user-images.githubusercontent.com/101466847/158088573-c234c289-4683-4fae-b5ff-f7f6c579c251.png)
