### ISSUE TITLE
Endless loop when launching the Dashboard in local

### ISSUE THREAD

**Issue by jincheng-jason** [YaoApp/yao#57]
Hi, I followed the instruction in `Getting started` and managed to start the server with `yao start`, but met endless loop when I hit the dashboard URL `http://127.0.0.1:5099/xiang/login/admin` in chrome, I'm using the MacOS and no error logs in both server side and Chrome console, just have a screenshot here, it's refreshing in the login page again and again, thanks:
Chrome version: Version 99.0.4844.51 (Official Build) (x86_64)
![image](https://user-images.githubusercontent.com/3085846/158082604-99b32116-c253-41a8-a97d-4d2016d04689.png)

**Comment by 41668895** [comment]
you can try to restart yao server.

**Comment by jincheng-jason** [comment]
> 

Restarted and cleared the chrome cache, still the same.

**Comment by jincheng-jason** [comment]
@trheyi Hi, I didn't see any logs in the console, and for the API response, it's really refreshing too fast to see the info inside: 
![image](https://user-images.githubusercontent.com/3085846/158908864-22beb291-58f2-4be4-858f-25fa0eda59e3.png)
