### ISSUE TITLE
[Bug] Error 1066 (42000): Not unique table/alias: 'api_user__rel__'

### ISSUE THREAD

**Issue by yflau** [YaoApp/yao#586]
## 发生了什么?
定义一个Model `API`，包含多个持有与`User` Model的hasOne关联的字段，但是查询会报错如下

`{
    "message": "[table] api yao.table.Search -> models.api.Paginate Error 1066 (42000): Not unique table/alias: 'api_user__rel__'",
    "code": 500,
    "context": null
}`

## 最小可复现例子（必需）

> Please provide a [minimal reproduction](https://stackoverflow.com/help/minimal-reproducible-example) then upload to your GitHub. 请提供 [最小重现](https://stackoverflow.com/help/minimal-reproducible-example)，并上传到你的 GitHub 仓库

## 复现步骤

**Steps to reproduce the behavior:** 1. 2.

Model dsl：

`{
    "name": "::Api",
    "table": {
        "name": "api",
        "label": "服务接口表"
    },
    "columns": [
        {
            "name": "id",
            "label": "ID",
            "type": "ID"
        },
        {
            "name": "name",
            "label": "名称",
            "type": "string",
            "length": 80,
            "index": true,
            "comment": "接口名称"
        },
        {
            "name": "pd_id",
            "label": "产品",
            "type": "bigInteger",
            "index": true,
            "comment": "产品负责人ID"
        },
        {
            "name": "rd_id",
            "label": "研发",
            "type": "bigInteger",
            "index": true,
            "comment": "研发负责人ID"
        }
    ],
    "relations": {
        "pd": {
            "name": "pd",
            "type": "hasOne",
            "model": "user",
            "key": "id",
            "foreign": "pd_id",
            "query": {
                "select": [
                    "id",
                    "name"
                ]
            }
        },
        "rd": {
            "name": "rd",
            "type": "hasOne",
            "model": "user",
            "key": "id",
            "foreign": "rd_id",
            "query": {
                "select": [
                    "id",
                    "name"
                ]
            }
        }
    },
    "values": [],
    "indexes": [],
    "option": {
        "timestamps": true,
        "soft_deletes": true
    }
}`

**Expected behavior** 1. 2.

配置tab之后，管理后台会显示如下错误：

`{
    "message": "[table] api yao.table.Search -> models.api.Paginate Error 1066 (42000): Not unique table/alias: 'api_user__rel__'",
    "code": 500,
    "context": null
}`

## Context

- **Yao Version( Detail Version )**:0.10.4
- **Xgen Version( Build Info )**:1.0
- **Platform**:macos

**Comment by trheyi** [comment]
https://github.com/YaoApp/yao/actions/runs/8866857348   @yflau  这个版本修复了
