### ISSUE TITLE
有生成项目的源码吗？想看看生成代码的结构以及生成项目，如何修改业务逻辑？

### ISSUE THREAD

**Issue by lchjczw** [YaoApp/yao#59]

**Comment by 41668895** [comment]
项目是整个框架一起部署的，不是单独生成源码部署，不能直接看到代码，如果要修改业务逻辑，直接在处理器和数据流中修改。所有的业务逻辑都在处理器也数据流里

**Comment by lchjczw** [comment]
那我没理解，如果不能看到代码，我如何部署？二进制？

**Comment by lchjczw** [comment]
这个空了在研究吧，我没看到我们的实现原理，所以看说了一堆，实际上也不知道你们这个做什么，只知道通过json可以编译生成代码，直接能运行，比如说数据存在哪里，支持哪些数据库，文档上一概没有呢，https://github.com/YaoApp/demo-crm 看了这个，感觉这个就是一个配置文档，通过yao来解析运行

**Comment by lchjczw** [comment]
在流里面处理，是不是就意味着，我需要做关联表，做排序查询这些都搞不了，查询字段，分布在多个表里面的也做不了，涉及到多表查询，分页问题，如果处理？

**Comment by trheyi** [comment]
@lchjczw  可以参考文档和示例应用。https://yaoapps.com/doc/c.%E9%AB%98%E7%BA%A7%E7%89%B9%E6%80%A7/b.%E6%95%B0%E6%8D%AE%E6%A8%A1%E5%9E%8B%E5%85%B3%E8%81%94
