### ISSUE TITLE
请问这个接口（ http://127.0.0.1:5099/api/pet/search）用postman调用时，具体参数是怎样的？

### ISSUE THREAD

**Issue by zhuangxupeng** [YaoApp/yao#62]

**Comment by zhuangxupeng** [comment]
{
      "path": "/search",
      "method": "GET",
      "guard": "-",
      "process": "models.pet.Paginate",
      "in": [":query-param", "$query.page", "$query.pagesize"],
      "out": {
        "status": 200,
        "type": "application/json"
      }
    }

可能是文档中存在部分错误，将接口改为上述后 **"in": [":query-param", "$query.page", "$query.pagesize"]**  ，测试成功了。

**Comment by nghialt** [comment]
It's really hard for me to find out there's type in the document `$quey.pagesize`, could you update this ASAP? 
<img width="714" alt="Screen Shot 2022-04-09 at 11 02 18" src="https://user-images.githubusercontent.com/1725216/162555535-9ba9f621-2a9f-4ab4-a2f7-e0f317db6972.png">
