### ISSUE TITLE
能开发微信小程序的接口吗？

### ISSUE THREAD

**Issue by iamdaiyuan** [YaoApp/yao#63]
是否能用来开发微信小程序的接口？
我看到都是json配置，不知道如何开发微信小程序，做过的朋友麻烦告知一下。

**Comment by iamdaiyuan** [comment]
> 可用作小程序的后端接口和WEB管理后台。

很不错。不知道有没有与微信小程序开发相关的demo？

**Comment by trheyi** [comment]
有 CRM 小程序端的计划，会随后续版本开源。
