### ISSUE TITLE
How to disable edit in table?

### ISSUE THREAD

**Issue by SuperGod** [YaoApp/yao#69]
How to disable edit in table?

**Comment by 41668895** [comment]
这就是区别
![image](https://user-images.githubusercontent.com/101466847/158714223-0055c6d8-55c1-40f5-83be-9ae16c7f7fb0.png)

**Comment by tengzhuofei** [comment]
![image](https://user-images.githubusercontent.com/49179198/180391417-bfa35f5e-10c5-4909-b60e-bab1a5ade26a.png)

**Comment by QJAutumn** [comment]
在edit的props里面写: "disabled":true
