### ISSUE TITLE
终端下运行脚本报错

### ISSUE THREAD

**Issue by lengxiaoyu6** [YaoApp/yao#70]
![image](https://user-images.githubusercontent.com/43517191/158733174-2aa38232-91ee-404c-84b4-ea821ae0de7a.png)

**Comment by trheyi** [comment]
@lengxiaoyu6  操作系统的版本是？ 以及完整的错误信息是什么？

**Comment by lengxiaoyu6** [comment]
Linux version 4.18.0-305.10.2.el8_4.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Tue Jul 20 17:25:16 UTC 2021

错误信息
Installed: /usr/local/bin/yao
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x75 pc=0x7f0bf91e7bd0]

runtime stack:
runtime.throw({0x2594bdf, 0x7f0bf9ca67c0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 21 [syscall]:
runtime.cgocall(0x11ca250, 0xc00005fd90)
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00005fd68 sp=0xc00005fd30 pc=0x41263c
net._C2func_getaddrinfo(0xc000046b30, 0x0, 0xc000274420, 0xc000010130)
        _cgo_gotypes.go:90 +0x56 fp=0xc00005fd90 sp=0xc00005fd68 pc=0x56ae76
net.cgoLookupIPCNAME.func1({0xc000046b30, 0x0, 0x0}, 0x25634e0, 0xc00005fe50)
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00005fde8 sp=0xc00005fd90 pc=0x56cbbf
net.cgoLookupIPCNAME({0x25521a2, 0x3}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00005ff38 sp=0xc00005fde8 pc=0x56c40d
net.cgoIPLookup(0x45c7c30, {0x25521a2, 0xc000046710}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00005ffa8 sp=0xc00005ff38 pc=0x56cc7b
net.cgoLookupIP·dwrap·25()
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00005ffe0 sp=0xc00005ffa8 pc=0x56d0f6
runtime.goexit()
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005ffe8 sp=0xc00005ffe0 pc=0x475361
created by net.cgoLookupIP
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net.(*Resolver).lookupIPAddr(0x45c7c20, {0x2d3a090, 0xc000138000}, {0x25521a2, 0xc0001159b0}, {0x25634e0, 0x9})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0xc0004eda78, {0x2d3a090, 0xc000138000}, {0x25521a2, 0x3}, {0x25634e0, 0xb})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/ipsock.go:288 +0x67a
net.ResolveTCPAddr({0x25521a2, 0x2a}, {0x25634e0, 0xb})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/tcpsock.go:77 +0xaf
github.com/yaoapp/yao/network.FreePort()
        /home/runner/work/yao/yao/network/ip.go:44 +0x65
github.com/yaoapp/yao/share.init.0()
        /home/runner/work/yao/yao/share/session.go:27 +0x19

goroutine 20 [select]:
net.cgoLookupIP({0x2d3a058, 0xc000158440}, {0x25521a2, 0x9}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x45c7c20, {0x2d3a058, 0xc000158440}, {0x25521a2, 0x3}, {0x25634e0, 0x9})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x2d3a058, 0xc000158440}, 0x0, {0x25521a2, 0x0}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x45c7c30, 0xc0000a21e0, {0xc000046710, 0xd}, 0x0)
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
Version: 
DONE

**Comment by lengxiaoyu6** [comment]
> @lengxiaoyu6 操作系统的版本是？ 以及完整的错误信息是什么？

Linux version 4.18.0-305.10.2.el8_4.x86_64 (mockbuild@kbuilder.bsys.centos.org) (gcc version 8.4.1 20200928 (Red Hat 8.4.1-1) (GCC)) #1 SMP Tue Jul 20 17:25:16 UTC 2021

错误信息：
Installed: /usr/local/bin/yao
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x75 pc=0x7fa04924fbd0]

runtime stack:
runtime.throw({0x2594bdf, 0x7fa04b5737c0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 6 [syscall]:
runtime.cgocall(0x11ca250, 0xc00005f590)
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/cgocall.go:156 +0x5c fp=0xc00005f568 sp=0xc00005f530 pc=0x41263c
net._C2func_getaddrinfo(0xc000422bb0, 0x0, 0xc000274840, 0xc000130030)
        _cgo_gotypes.go:90 +0x56 fp=0xc00005f590 sp=0xc00005f568 pc=0x56ae76
net.cgoLookupIPCNAME.func1({0xc000422bb0, 0x0, 0x0}, 0x25634e0, 0xc00005f650)
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x9f fp=0xc00005f5e8 sp=0xc00005f590 pc=0x56cbbf
net.cgoLookupIPCNAME({0x25521a2, 0x3}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:163 +0x16d fp=0xc00005f738 sp=0xc00005f5e8 pc=0x56c40d
net.cgoIPLookup(0x45c7c30, {0x25521a2, 0xc000046d90}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:220 +0x3b fp=0xc00005f7a8 sp=0xc00005f738 pc=0x56cc7b
net.cgoLookupIP·dwrap·25()
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x36 fp=0xc00005f7e0 sp=0xc00005f7a8 pc=0x56d0f6
runtime.goexit()
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/asm_amd64.s:1581 +0x1 fp=0xc00005f7e8 sp=0xc00005f7e0 pc=0x475361
created by net.cgoLookupIP
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:230 +0x125

goroutine 1 [select, locked to thread]:
net.(*Resolver).lookupIPAddr(0x45c7c20, {0x2d3a090, 0xc000138000}, {0x25521a2, 0xc000115950}, {0x25634e0, 0x9})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:302 +0x5c7
net.(*Resolver).internetAddrList(0xc0004eda78, {0x2d3a090, 0xc000138000}, {0x25521a2, 0x3}, {0x25634e0, 0xb})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/ipsock.go:288 +0x67a
net.ResolveTCPAddr({0x25521a2, 0x2a}, {0x25634e0, 0xb})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/tcpsock.go:77 +0xaf
github.com/yaoapp/yao/network.FreePort()
        /home/runner/work/yao/yao/network/ip.go:44 +0x65
github.com/yaoapp/yao/share.init.0()
        /home/runner/work/yao/yao/share/session.go:27 +0x19

goroutine 21 [select]:
net.cgoLookupIP({0x2d3a058, 0xc000158380}, {0x25521a2, 0x9}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/cgo_unix.go:231 +0x1b7
net.(*Resolver).lookupIP(0x45c7c20, {0x2d3a058, 0xc000158380}, {0x25521a2, 0x3}, {0x25634e0, 0x9})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup_unix.go:97 +0x128
net.glob..func1({0x2d3a058, 0xc000158380}, 0x0, {0x25521a2, 0x0}, {0x25634e0, 0x0})
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/hook.go:23 +0x3d
net.(*Resolver).lookupIPAddr.func1()
        /opt/hostedtoolcache/go/1.17.7/x64/src/net/lookup.go:296 +0x9f
internal/singleflight.(*Group).doCall(0x45c7c30, 0xc0000963c0, {0xc000046d90, 0xd}, 0x0)
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:95 +0x3b
created by internal/singleflight.(*Group).DoChan
        /opt/hostedtoolcache/go/1.17.7/x64/src/internal/singleflight/singleflight.go:88 +0x2f1
Version: 
DONE

**Comment by Earchaut** [comment]
CentOS 8.2运行也是这个报错
