### ISSUE TITLE
关于 DSL / ORM / 企业级UI  等低代码架构设计的一系列建议

### ISSUE THREAD

**Issue by cabbage89** [YaoApp/yao#71]
1. 放弃 JSON 作为 DSL , 回归 XML+XML Schema, 好处是易扩展, 可以在开发时代码提示,JSON 根本不适合做 DSL
2. 后台 UI 太丑了, 管理系统需要紧凑的 UI, 尤其是 ERP 这种需要更高的屏幕利用率,当前 UI 过于松散, 间距过大, 屏幕浪费严重,不适合日常使用
3. 定位后台管理系统需要支持页内 tab 功能,在一个页面内打开多个功能 tab,避免被新打开的功能覆盖

**Comment by cabbage89** [comment]
来自东欧的另一人上vue  golang低代码平台 https://github.com/cortezaproject , 它用的 YAML 作为 DSL 是一大败笔,
全球低代码开发目前只有XML作为 DSL 的方案让人更容易接受和流行.

golang低代码的 ORM选型最好是 [Facebook ent](https://entgo.io/zh/docs/getting-started/ ) ,它与 java 的 hibernate JPA非常类似,适合 DDD

**Comment by trheyi** [comment]
感谢建议。

**Comment by BeanWei** [comment]
xml和ent 并不太认同，json不适合 xml同样不适合，dsl可以基于go语言本身来做，再不济可以用hcl，用语言本身来做 不管是从复用还是代码提示来说都有天然得罪优势。
然后说下ent，这个非常不适合做低代码开发，低代码开发个人认为并不需要orm，甚至不需要sql，orm不利于表达，这块可以上 edgedb。

**Comment by BeanWei** [comment]
这个问题可以移步到讨论区继续讨论，哈哈
