### ISSUE TITLE
进入Yao后台管理系统中，用户管理修改密码失败

### ISSUE THREAD

**Issue by ZiTonzong** [YaoApp/yao#72]
如题，新建或者修改用户密码的时候，只有带有大小写字母和字符“+”的密码可以通过验证，个人觉得很不合理，并且也没有在前端予以说明，这样在修改密码的时候让用户很困惑
![image](https://user-images.githubusercontent.com/40049843/158932977-98538866-c9f7-4787-aa3d-5ea09d8eeb7f.png)

**Comment by ZiTonzong** [comment]
![image](https://user-images.githubusercontent.com/40049843/158933071-2dc552da-219b-4c68-bf9b-e1b0f98d7cd3.png)
加了“+”就可以修改成功了

**Comment by trheyi** [comment]
可以在日志中查看到错误信息，xgen新版会优化这些报错信息。
