### ISSUE TITLE
登陆页面验证码不显示

### ISSUE THREAD

**Issue by davis882** [YaoApp/yao#73]
你好，登陆页面 /xiang/login/user  验证码不显示
审查元素：url("undefined")
win10+wsl+chrome  

第一次测试时验证码可以显示，进入系统后修改了管理员mail和密码，退出重新登陆就没有验证码了
项目删除重建后，验证码依然不能显示。

**Comment by 41668895** [comment]
请登录 /xiang/login/admin，检查一下你的url

**Comment by davis882** [comment]
> 请登录 /xiang/login/admin，检查一下你的url

/xiang/login/admin 验证码可以正常使用，但登出账号后自动跳转到 /xiang/login/user 是什么原因
 /xiang/login/user 这个页面是做什么用的，谢谢
