### ISSUE TITLE
session无法使用

### ISSUE THREAD

**Issue by duyisu** [YaoApp/yao#79]
通过session.set设置了user信息，在table的search api里面通过wheres配置只能看到自己提交的数据，$user.id为0，无法获取到，$session也不能用

**Comment by duyisu** [comment]
{
  "label": "当前用户的记录",
  "version": "1.0.0",
  "description": "读取当前用户的记录",
  "nodes": [
     {
      "name": "User",
      "process": "session.get",
      "args": ["user"]
    },
     {
      "name": "Visitant",
      "process": "models.visitant.paginate",
      "args": ["{{$in.0}}","{{$in.1}}","{{$in.2}}"],
      "outs": ["{{$out.data}}"]
    }
  ],
  "output": { "in": "{{$res.Visitant}}", "user": "{{$res.User}}" }
}



登录后的接口返回结果为：
{in: [[{acid: "阴性", acid_date: null, address_string: null, control_mode: "14+7",…},…]], user: null}
in: [[{acid: "阴性", acid_date: null, address_string: null, control_mode: "14+7",…},…]]
0: [{acid: "阴性", acid_date: null, address_string: null, control_mode: "14+7",…},…]
0: {acid: "阴性", acid_date: null, address_string: null, control_mode: "14+7",…}
1: {acid: "阴性", acid_date: null, address_string: null, control_mode: "14+7",…}
2: {acid: "阴性", acid_date: null, address_string: null, control_mode: "14+7",…}
user: null

**Comment by trheyi** [comment]
这个是已知BUG，0.9.2 已修复。 替换  /user/local/bin/yao   `chmod +x /usr/local/bin/yao`
https://release-bj.yaoapps.com/archives/yao-0.9.2-linux-amd64   Linux
https://release-bj.yaoapps.com/archives/yao-0.9.2-darwin-amd64  Mac
https://release-bj.yaoapps.com/archives/yao-0.9.2-darwin-arm64 Mac M1

**Comment by duyisu** [comment]
太感谢了，最近一个小项目用咱们框架，发现太棒了，等我有时间一定贡献源码

---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年3月22日(周二) 下午4:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [YaoApp/yao] session无法使用 (Issue #79)




 
这个是已知BUG，0.9.2 已修复。 替换  /user/local/bin/yao   chmod +x /usr/local/bin/yao
 https://release-bj.yaoapps.com/archives/yao-0.9.2-linux-amd64   Linux
 https://release-bj.yaoapps.com/archives/yao-0.9.2-darwin-amd64  Mac
 https://release-bj.yaoapps.com/archives/yao-0.9.2-darwin-arm64 Mac M1

**Comment by trheyi** [comment]
感谢支持，期待与我们一起完善。
