### ISSUE TITLE
插件编写

### ISSUE THREAD

**Issue by boyuwu** [YaoApp/yao#82]
插件里飞书登录的DEMO，运行后报错Plugin：feishu；尚未加载。想请问会是什么原因导致的？以检查命令无误

**Comment by boyuwu** [comment]
文件夹命名为plugins，执行命令yao run plugin.feishu.AuthURL可以调用.so文件，但是现在报错exec format error。请问一下这个原因是？

**Comment by liushuainice** [comment]
yao run plugins.xxxxx

试一下

**Comment by boyuwu** [comment]
yao run plugins.feishu.AuthURl "xxxx" "login" 这种方式？试过了还是一样的报错

**Comment by liushuainice** [comment]
我测试官网的例子是没问题的，你试一下我改造的demo呢



package main

//go build -o ./temp.so .

import (
	"encoding/json"
	"github.com/yaoapp/kun/grpc"
	"io"
	"os"
)

//路由
func getConnAndList(conn string) func(args interface{}) map[string]interface{} {
	maps := map[string]func(args interface{}) map[string]interface{}{
		"help":  gmHelp,
		"hello": Hello,
	}
	return maps[conn]
}

//example 1
func gmHelp(args interface{}) map[string]interface{} {
	m := map[string]interface{}{}
	m["flag"] = true
	m["args"] = args
	return m
}

//example 2
func Hello(args interface{}) map[string]interface{} {
	var str []string
	bytes, _ := json.Marshal(args)
	_ = json.Unmarshal(bytes, &str)

	v := map[string]interface{}{"code": 400, "message": "缺少回调地址参数", "args": args}
	if len(str) < 1 {
		v["flag"] = 1
		return v
	}
	v = map[string]interface{}{"code": 200, "message": "解析成功", "args": args}
	v["flag"] = 2

	return map[string]interface{}{"hello": "world", "args": args, "args1": str[0]}

}

type Temp struct{ grpc.Plugin }

// Exec 读取
func (temp *Temp) Exec(name string, args ...interface{}) (*grpc.Response, error) {
	var v interface{}

	connFunc := getConnAndList(name)
	if connFunc != nil { //查不到方法会返回nil
		v = connFunc(&args)
	} else {
		v = map[string]interface{}{"msg": "no find method", "name": name, "args": args}
	}

	bytes, err := json.Marshal(v)
	if err != nil {
		return nil, err
	}
	return &grpc.Response{Bytes: bytes, Type: "map"}, nil
}

func main() {
	var output io.Writer = os.Stdout
	plugin := &Temp{}
	plugin.SetLogger(output, grpc.Trace)
	grpc.Serve(plugin)
}

**Comment by boyuwu** [comment]
> 我测试官网的例子是没问题的，你试一下我改造的demo呢
> 
> package main
> 
> //go build -o ./temp.so .
> 
> import ( "encoding/json" "github.com/yaoapp/kun/grpc" "io" "os" )
> 
> //路由 func getConnAndList(conn string) func(args interface{}) map[string]interface{} { maps := map[string]func(args interface{}) map[string]interface{}{ "help": gmHelp, "hello": Hello, } return maps[conn] }
> 
> //example 1 func gmHelp(args interface{}) map[string]interface{} { m := map[string]interface{}{} m["flag"] = true m["args"] = args return m }
> 
> //example 2 func Hello(args interface{}) map[string]interface{} { var str []string bytes, _ := json.Marshal(args) _ = json.Unmarshal(bytes, &str)
> 
> ```
> v := map[string]interface{}{"code": 400, "message": "缺少回调地址参数", "args": args}
> if len(str) < 1 {
> 	v["flag"] = 1
> 	return v
> }
> v = map[string]interface{}{"code": 200, "message": "解析成功", "args": args}
> v["flag"] = 2
> 
> return map[string]interface{}{"hello": "world", "args": args, "args1": str[0]}
> ```
> 
> }
> 
> type Temp struct{ grpc.Plugin }
> 
> // Exec 读取 func (temp *Temp) Exec(name string, args ...interface{}) (*grpc.Response, error) { var v interface{}
> 
> ```
> connFunc := getConnAndList(name)
> if connFunc != nil { //查不到方法会返回nil
> 	v = connFunc(&args)
> } else {
> 	v = map[string]interface{}{"msg": "no find method", "name": name, "args": args}
> }
> 
> bytes, err := json.Marshal(v)
> if err != nil {
> 	return nil, err
> }
> return &grpc.Response{Bytes: bytes, Type: "map"}, nil
> ```
> 
> }
> 
> func main() { var output io.Writer = os.Stdout plugin := &Temp{} plugin.SetLogger(output, grpc.Trace) grpc.Serve(plugin) }

**Comment by boyuwu** [comment]
找到原因了，编译环境的问题
