### ISSUE TITLE
yao 在菜单中如何支持自定义页面显示

### ISSUE THREAD

**Issue by dlvkin** [YaoApp/yao#84]
yao菜单栏,菜单导航栏,container 所在界面,我现在问题是点击菜单栏,container  中如何显示我自定义页面.
   yao 能改解决大部分前端页面渲染格式问题,但是登录以后, 在 kanban,table,screen,page 等类型渲染出来页面都是页面都没法实现,比较复杂页面和交互,我在ui/ 下面自定义的demo/index.html css js ,如何在我菜单中访问? 现在默认路由都是/xiang/前缀,怎么才能改支持我的需求?

**Comment by MatrixAge** [comment]
https://github.com/YaoApp/xiang-app/search?q=iframe&type=commits

check this.
