### ISSUE TITLE
关于前端访问接口跨域

### ISSUE THREAD

**Issue by 809388027** [YaoApp/yao#85]
你好，我是一个前端开发人员，我使用了YAO创建了模型以及接口，当我用curl以及postman调用接口时没有异常，然后尝试使用自己的项目调用创建的接口时访问跨域，虽然可以靠代理解决，但我不想这样做，请问一下咱们有相关的配置吗或是就是这么设计的只有在YAO中生成的界面才可以调用

**Comment by MatrixAge** [comment]
yao提供的是api服务，前端跨域问题请自行解决

**Comment by 809388027** [comment]
好的，谢谢
