### ISSUE TITLE
Yao web services mode

### ISSUE THREAD

**Issue by andi-souwer** [YaoApp/yao#86]
使用源码调试的时候，web页面默认打开当前目录`ui/index.html`，是否是需要将xgen编译成静态文件放到源码ui/目录下?

**Comment by MatrixAge** [comment]
![image](https://user-images.githubusercontent.com/25472851/159887598-ed8e7d8d-dbfc-4340-874f-361d74616128.png)

https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/a.%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97

**Comment by andi-souwer** [comment]
> ![image](https://user-images.githubusercontent.com/25472851/159887598-ed8e7d8d-dbfc-4340-874f-361d74616128.png)
> 
> https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/a.%E5%85%A5%E9%97%A8%E6%8C%87%E5%8D%97

不是怎么启动服务，是静态页面放哪？

**Comment by andi-souwer** [comment]
是的，我将`xgen`编译完成后的静态文件放在`yao`项目ui`目录中，再进行编译`yao`项目后，使用`demo-crm`项目访问，页面依然是`Yao web services mode`，显然，是没有找到编译后`xgen`。不知道哪里出错了？

![image](https://user-images.githubusercontent.com/59073235/160036668-baf00c04-bf24-4f52-8792-93f73b2467f7.png)

**Comment by andi-souwer** [comment]
> 通过 /xiang/ 访问的页面是xgen编译成静态文件内置在yao里面的。

换句话说，不清楚`yao`的编译的具体过程

**Comment by andi-souwer** [comment]
> > 通过 /xiang/ 访问的页面是xgen编译成静态文件内置在yao里面的。
> 
> 换句话说，不清楚`yao`的编译的具体过程

前端静态文件放在`yao/ui/`目录下是对了，确实是启动位置的问题，已经可以开始源码的调试了
