### ISSUE TITLE
Remote database

### ISSUE THREAD

**Issue by lau1944** [YaoApp/yao#9]
After taking a look at the documentation, I did not find a way to interact with the remote database, is that any method to deal with that or would it be available in the future?

**Comment by thlz998** [comment]
https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/b.%E5%AE%89%E8%A3%85%E8%B0%83%E8%AF%95

![image](https://user-images.githubusercontent.com/36218343/155648630-b2af6371-5282-4950-b6a5-771922c1f358.png)
