### ISSUE TITLE
Please Add Mongodb Datebase

### ISSUE THREAD

**Issue by emengweb** [YaoApp/yao#91]
Mongodb Datebase batter more than Mysql in some project, advice add MongoDB datebase support.

**Comment by trheyi** [comment]
There is a clear plan for support, but it is not a high priority.

https://github.com/YaoApp/gou/tree/main/kv
https://github.com/YaoApp/gou/blob/main/runtime/yao/objects/store_test.go JavaScript API
https://github.com/YaoApp/gou/blob/main/store_test.go Process

docker pull yaoapp/yao:0.9.2-amd64
