### ISSUE TITLE
windows源码构建

### ISSUE THREAD

**Issue by Acidhj** [YaoApp/yao#94]
# rogchap.com/v8go
E:/gcc/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/8.1.0/../../../../x86_64-w64-mingw32/bin/ld.exe: cannot find -lv8
collect2.exe: error: ld returned 1 exit status

**Comment by trheyi** [comment]
请使用 docker 或虚拟机 在 Linux 系统下构建

**Comment by 7117** [comment]
你好，请问我使用linux进行构建，报错
`root@PW9013436:/da/yao# make
echo "mode: count" > cfoverage.out
for d in github.com/yaoapp/yao github.com/yaoapp/yao/api github.com/yaoapp/yao/app github.com/yaoapp/yao/chart github.com/yaoapp/yao/cmd github.com/yaoapp/yao/data github.com/yaoapp/yao/engine github.com/yaoapp/yao/flow github.com/yaoapp/yao/helper github.com/yaoapp/yao/importer github.com/yaoapp/yao/importer/csv github.com/yaoapp/yao/importer/from github.com/yaoapp/yao/importer/xlsx github.com/yaoapp/yao/model github.com/yaoapp/yao/network github.com/yaoapp/yao/page github.com/yaoapp/yao/plugin github.com/yaoapp/yao/query github.com/yaoapp/yao/script github.com/yaoapp/yao/server github.com/yaoapp/yao/service github.com/yaoapp/yao/share github.com/yaoapp/yao/store github.com/yaoapp/yao/table github.com/yaoapp/yao/user github.com/yaoapp/yao/workflow github.com/yaoapp/yao/xfs; do \
        go test -tags "" -v -covermode=count -coverprofile=profile.out -coverpkg=$(echo $d | sed "s/\/test$//g") $d > tmp.out; \
        cat tmp.out; \
        if grep -q "^--- FAIL 111111" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        elif grep -q "build failed 22222" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        elif grep -q "setup failed 333333" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        elif grep -q "runtime error 444444" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        fi; \
        if [ -f profile.out ]; then \
                cat profile.out | grep -v "mode:" >> coverage.out; \
                rm profile.out; \
        fi; \
done
=== RUN   TestCommandVersion
0.9.2
--- PASS: TestCommandVersion (0.00s)
=== RUN   TestCommandMigrate
time="2022-04-01T15:01:09+08:00" level=warning msg="Can't load env file. open /da/yao/.env: no such file or directory"
TRY: yao migrate --force
Fatal: Migrate is not allowed on production mode.
--- PASS: TestCommandMigrate (0.00s)
=== RUN   TestCommandStart
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 14 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao   0.181s
FAIL
=== RUN   TestLoad
    api_test.go:30:
                Error Trace:    api_test.go:30
                                                        api_test.go:16
                Error:          Not equal:
                                expected: 4
                                actual  : 0
                Test:           TestLoad
    api_test.go:31:
                Error Trace:    api_test.go:31
                                                        api_test.go:16
                Error:          Not equal:
                                expected: 1
                                actual  : 0
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 21.1% of statements in github.com/yaoapp/yao/api
FAIL    github.com/yaoapp/yao/api       0.129s
FAIL
=== RUN   TestLoad
    app_test.go:13:
                Error Trace:    app_test.go:13
                Error:          Not equal:
                                expected: "Yao"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Yao
                                +
                Test:           TestLoad
    app_test.go:14:
                Error Trace:    app_test.go:14
                Error:          Not equal:
                                expected: "Xiang"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Xiang
                                +
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 57.1% of statements in github.com/yaoapp/yao/app
FAIL    github.com/yaoapp/yao/app       0.133s
FAIL`

**Comment by 7117** [comment]
我使用linux环境make报错了，如下

**Comment by 7117** [comment]
`root@PW9013436:/da/yao# make
echo "mode: count" > cfoverage.out
for d in github.com/yaoapp/yao github.com/yaoapp/yao/api github.com/yaoapp/yao/app github.com/yaoapp/yao/chart github.com/yaoapp/yao/cmd github.com/yaoapp/yao/data github.com/yaoapp/yao/engine github.com/yaoapp/yao/flow github.com/yaoapp/yao/helper github.com/yaoapp/yao/importer github.com/yaoapp/yao/importer/csv github.com/yaoapp/yao/importer/from github.com/yaoapp/yao/importer/xlsx github.com/yaoapp/yao/model github.com/yaoapp/yao/network github.com/yaoapp/yao/page github.com/yaoapp/yao/plugin github.com/yaoapp/yao/query github.com/yaoapp/yao/script github.com/yaoapp/yao/server github.com/yaoapp/yao/service github.com/yaoapp/yao/share github.com/yaoapp/yao/store github.com/yaoapp/yao/table github.com/yaoapp/yao/user github.com/yaoapp/yao/workflow github.com/yaoapp/yao/xfs; do \
        go test -tags "" -v -covermode=count -coverprofile=profile.out -coverpkg=$(echo $d | sed "s/\/test$//g") $d > tmp.out; \
        cat tmp.out; \
        if grep -q "^--- FAIL 111111" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        elif grep -q "build failed 22222" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        elif grep -q "setup failed 333333" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        elif grep -q "runtime error 444444" tmp.out; then \
                rm tmp.out; \
                exit 1; \
        fi; \
        if [ -f profile.out ]; then \
                cat profile.out | grep -v "mode:" >> coverage.out; \
                rm profile.out; \
        fi; \
done
=== RUN   TestCommandVersion
0.9.2
--- PASS: TestCommandVersion (0.00s)
=== RUN   TestCommandMigrate
time="2022-04-01T15:01:09+08:00" level=warning msg="Can't load env file. open /da/yao/.env: no such file or directory"
TRY: yao migrate --force
Fatal: Migrate is not allowed on production mode.
--- PASS: TestCommandMigrate (0.00s)
=== RUN   TestCommandStart
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 14 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao   0.181s
FAIL
=== RUN   TestLoad
    api_test.go:30:
                Error Trace:    api_test.go:30
                                                        api_test.go:16
                Error:          Not equal:
                                expected: 4
                                actual  : 0
                Test:           TestLoad
    api_test.go:31:
                Error Trace:    api_test.go:31
                                                        api_test.go:16
                Error:          Not equal:
                                expected: 1
                                actual  : 0
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 21.1% of statements in github.com/yaoapp/yao/api
FAIL    github.com/yaoapp/yao/api       0.129s
FAIL
=== RUN   TestLoad
    app_test.go:13:
                Error Trace:    app_test.go:13
                Error:          Not equal:
                                expected: "Yao"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Yao
                                +
                Test:           TestLoad
    app_test.go:14:
                Error Trace:    app_test.go:14
                Error:          Not equal:
                                expected: "Xiang"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -Xiang
                                +
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 57.1% of statements in github.com/yaoapp/yao/app
FAIL    github.com/yaoapp/yao/app       0.133s
FAIL
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 22 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/chart     0.165s
FAIL
?       github.com/yaoapp/yao/cmd       [no test files]
?       github.com/yaoapp/yao/data      [no test files]
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 13 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/engine    0.174s
FAIL
=== RUN   TestLoad
    flow_test.go:23:
                Error Trace:    flow_test.go:23
                                                        flow_test.go:15
                Error:          Not equal:
                                expected: 24
                                actual  : 0
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 18.2% of statements in github.com/yaoapp/yao/flow
FAIL    github.com/yaoapp/yao/flow      0.128s
FAIL
=== RUN   TestArrayPluck
--- PASS: TestArrayPluck (0.00s)
=== RUN   TestArraySplit
--- PASS: TestArraySplit (0.00s)
=== RUN   TestArrayTree
--- PASS: TestArrayTree (0.00s)
=== RUN   TestProcessArrayPluck
--- PASS: TestProcessArrayPluck (0.00s)
=== RUN   TestProcessArraySplit
--- PASS: TestProcessArraySplit (0.00s)
=== RUN   TestProcessArrayUnique
--- PASS: TestProcessArrayUnique (0.00s)
=== RUN   TestProcessArrayIndexes
--- PASS: TestProcessArrayIndexes (0.00s)
=== RUN   TestProcessArrayGet
--- PASS: TestProcessArrayGet (0.00s)
=== RUN   TestCaptcha
--- PASS: TestCaptcha (0.01s)
=== RUN   TestProcessCaptcha
--- PASS: TestProcessCaptcha (0.00s)
=== RUN   TestCase
--- PASS: TestCase (0.00s)
=== RUN   TestProcessCase
--- PASS: TestProcessCase (0.00s)
=== RUN   TestCondition
--- PASS: TestCondition (0.00s)
=== RUN   TestProcessThrow
--- PASS: TestProcessThrow (0.00s)
=== RUN   TestProcessReturn
--- PASS: TestProcessReturn (0.00s)
=== RUN   TestProcessEnv
--- PASS: TestProcessEnv (0.00s)
=== RUN   TestProcessEnvMulti
--- PASS: TestProcessEnvMulti (0.00s)
=== RUN   TestProcessHexToString
time="2022-04-01T15:02:20+08:00" level=error msg="HexToString: type does not support" input=1024
--- PASS: TestProcessHexToString (0.00s)
=== RUN   TestProcessHexToStringInFlow
    hex_test.go:33:
                Error Trace:    hex_test.go:33
                Error:          Expected nil, but got: &errors.errorString{s:"Flow:helper.hextostring; 尚未加载"}
                Test:           TestProcessHexToStringInFlow
    hex_test.go:34:
                Error Trace:    hex_test.go:34
                Error:          Not equal:
                                expected: string("6162")
                                actual  : <nil>(<nil>)
                Test:           TestProcessHexToStringInFlow
--- FAIL: TestProcessHexToStringInFlow (0.00s)
=== RUN   TestProcessHexToStringInScript
    hex_test.go:42:
                Error Trace:    hex_test.go:42
                Error:          Expected nil, but got: &errors.errorString{s:"The helper does not loaded (0)"}
                Test:           TestProcessHexToStringInScript
    hex_test.go:43:
                Error Trace:    hex_test.go:43
                Error:          Not equal:
                                expected: string("6162")
                                actual  : <nil>(<nil>)
                Test:           TestProcessHexToStringInScript
    hex_test.go:46:
                Error Trace:    hex_test.go:46
                Error:          Expected nil, but got: &errors.errorString{s:"The helper does not loaded (0)"}
                Test:           TestProcessHexToStringInScript
    hex_test.go:47:
                Error Trace:    hex_test.go:47
                Error:          Not equal:
                                expected: string("0001")
                                actual  : <nil>(<nil>)
                Test:           TestProcessHexToStringInScript
--- FAIL: TestProcessHexToStringInScript (0.00s)
=== RUN   TestProcessBufferInScript
    hex_test.go:55:
                Error Trace:    hex_test.go:55
                Error:          Expected nil, but got: &errors.errorString{s:"The helper does not loaded (0)"}
                Test:           TestProcessBufferInScript
    hex_test.go:58:
                Error Trace:    hex_test.go:58
                Error:          Should be true
                Test:           TestProcessBufferInScript
    hex_test.go:59:
                Error Trace:    hex_test.go:59
                Error:          Not equal:
                                expected: []byte{0x0, 0x1}
                                actual  : []byte{}

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,3 +1,2 @@
                                -([]uint8) (len=2) {
                                - 00000000  00 01                                             |..|
                                +([]uint8) {
                                 }
                Test:           TestProcessBufferInScript
--- FAIL: TestProcessBufferInScript (0.00s)
=== RUN   TestIF
--- PASS: TestIF (0.00s)
=== RUN   TestProcessIF
--- PASS: TestProcessIF (0.00s)
=== RUN   TestJwt
time="2022-04-01T15:02:22+08:00" level=error msg="JWT ParseWithClaims Error: token is expired by 1s"
--- PASS: TestJwt (2.00s)
=== RUN   TestProcessJwt
time="2022-04-01T15:02:24+08:00" level=error msg="JWT ParseWithClaims Error: token is expired by 1s"
--- PASS: TestProcessJwt (2.00s)
=== RUN   TestProcessMapDel
--- PASS: TestProcessMapDel (0.00s)
=== RUN   TestProcessGetSet
--- PASS: TestProcessGetSet (0.00s)
=== RUN   TestProcessMapKeys
--- PASS: TestProcessMapKeys (0.00s)
=== RUN   TestProcessMapValues
--- PASS: TestProcessMapValues (0.00s)
=== RUN   TestProcessMapMultiDel
--- PASS: TestProcessMapMultiDel (0.00s)
=== RUN   TestProcessMapToArray
--- PASS: TestProcessMapToArray (0.00s)
=== RUN   TestPassword
--- PASS: TestPassword (0.00s)
=== RUN   TestProcessPassword
--- PASS: TestProcessPassword (0.00s)
=== RUN   TestProcessStrConcat
--- PASS: TestProcessStrConcat (0.00s)
FAIL
coverage: 69.7% of statements in github.com/yaoapp/yao/helper
FAIL    github.com/yaoapp/yao/helper    4.173s
FAIL
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 10 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/importer  0.139s
FAIL
?       github.com/yaoapp/yao/importer/csv      [no test files]
?       github.com/yaoapp/yao/importer/from     [no test files]
?       github.com/yaoapp/yao/importer/xlsx     [no test files]
=== RUN   TestLoad
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 41 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/model     0.136s
FAIL
=== RUN   TestIP
--- PASS: TestIP (0.00s)
=== RUN   TestProcessIP
--- PASS: TestProcessIP (0.00s)
=== RUN   TestFreePort
--- PASS: TestFreePort (0.10s)
=== RUN   TestProcessFreePort
--- PASS: TestProcessFreePort (0.00s)
=== RUN   TestRequestGetHtml
    request_test.go:13:
                Error Trace:    request_test.go:13
                Error:          Not equal:
                                expected: 200
                                actual  : 403
                Test:           TestRequestGetHtml
    request_test.go:14:
                Error Trace:    request_test.go:14
                Error:          Not equal:
                                expected: <nil>(<nil>)
                                actual  : map[string]interface {}(map[string]interface {}{"documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting", "message":"API rate limit exceeded for 129.227.150.231. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"})
                Test:           TestRequestGetHtml
--- FAIL: TestRequestGetHtml (0.37s)
=== RUN   TestRequestGetJSON
    request_test.go:19:
                Error Trace:    request_test.go:19
                Error:          Not equal:
                                expected: 200
                                actual  : 403
                Test:           TestRequestGetJSON
    request_test.go:21:
                Error Trace:    request_test.go:21
                Error:          Not equal:
                                expected: string("https://github.com/YaoApp")
                                actual  : <nil>(<nil>)
                Test:           TestRequestGetJSON
--- FAIL: TestRequestGetJSON (0.38s)
=== RUN   TestRequestPost
--- PASS: TestRequestPost (0.97s)
=== RUN   TestRequestPostJSON
--- PASS: TestRequestPostJSON (0.62s)
=== RUN   TestRequestProcessGet
    request_test.go:39:
                Error Trace:    request_test.go:39
                Error:          Not equal:
                                expected: 200
                                actual  : 403
                Test:           TestRequestProcessGet
    request_test.go:40:
                Error Trace:    request_test.go:40
                Error:          Not equal:
                                expected: <nil>(<nil>)
                                actual  : map[string]interface {}(map[string]interface {}{"documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting", "message":"API rate limit exceeded for 129.227.150.231. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"})
                Test:           TestRequestProcessGet
--- FAIL: TestRequestProcessGet (0.38s)
=== RUN   TestRequestProcessPost
--- PASS: TestRequestProcessPost (0.61s)
=== RUN   TestRequestProcessPostJSON
--- PASS: TestRequestProcessPostJSON (0.60s)
=== RUN   TestRequestProcessSend
    request_test.go:64:
                Error Trace:    request_test.go:64
                Error:          Not equal:
                                expected: 200
                                actual  : 403
                Test:           TestRequestProcessSend
    request_test.go:65:
                Error Trace:    request_test.go:65
                Error:          Not equal:
                                expected: <nil>(<nil>)
                                actual  : map[string]interface {}(map[string]interface {}{"documentation_url":"https://docs.github.com/rest/overview/resources-in-the-rest-api#rate-limiting", "message":"API rate limit exceeded for 129.227.150.231. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)"})
                Test:           TestRequestProcessSend
--- FAIL: TestRequestProcessSend (0.37s)
FAIL
coverage: 66.7% of statements in github.com/yaoapp/yao/network
FAIL    github.com/yaoapp/yao/network   4.444s
FAIL
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 51 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/page      0.159s
FAIL
=== RUN   TestLoad
    plugin_test.go:24:
                Error Trace:    plugin_test.go:24
                                                        plugin_test.go:16
                Error:          Not equal:
                                expected: 1
                                actual  : 0
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 33.3% of statements in github.com/yaoapp/yao/plugin
FAIL    github.com/yaoapp/yao/plugin    0.136s
FAIL
?       github.com/yaoapp/yao/query     [no test files]
=== RUN   TestScript
    script_test.go:18:
                Error Trace:    script_test.go:18
                Error:          Expected nil, but got: &errors.errorString{s:"The time does not loaded (0)"}
                Test:           TestScript
    script_test.go:19:
                Error Trace:    script_test.go:19
                Error:          Not equal:
                                expected: string("name:world")
                                actual  : <nil>(<nil>)
                Test:           TestScript
--- FAIL: TestScript (0.00s)
FAIL
coverage: 16.7% of statements in github.com/yaoapp/yao/script
FAIL    github.com/yaoapp/yao/script    0.025s
FAIL
=== RUN   TestLoad
    socket_test.go:36:
                Error Trace:    socket_test.go:36
                                                        socket_test.go:14
                Error:          Not equal:
                                expected: 2
                                actual  : 0
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
=== RUN   TestProcessStart
--- PASS: TestProcessStart (0.00s)
=== RUN   TestProcessConnect
--- PASS: TestProcessConnect (0.00s)
FAIL
coverage: 16.2% of statements in github.com/yaoapp/yao/server
FAIL    github.com/yaoapp/yao/server    0.127s
FAIL
?       github.com/yaoapp/yao/service   [no test files]
=== RUN   TestGetQueryParam
--- PASS: TestGetQueryParam (0.05s)
=== RUN   TestColumn
    importable_test.go:21:
                Error Trace:    importable_test.go:21
                Error:          Not equal:
                                expected: "upload"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -upload
                                +
                Test:           TestColumn
    importable_test.go:22:
                Error Trace:    importable_test.go:22
                Error:          Not equal:
                                expected: string(":logo")
                                actual  : <nil>(<nil>)
                Test:           TestColumn
    importable_test.go:23:
                Error Trace:    importable_test.go:23
                Error:          Not equal:
                                expected: "image"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -image
                                +
                Test:           TestColumn
    importable_test.go:24:
                Error Trace:    importable_test.go:24
                Error:          Not equal:
                                expected: float64(40)
                                actual  : <nil>(<nil>)
                Test:           TestColumn
    importable_test.go:25:
                Error Trace:    importable_test.go:25
                Error:          Not equal:
                                expected: float64(40)
                                actual  : <nil>(<nil>)
                Test:           TestColumn
    importable_test.go:26:
                Error Trace:    importable_test.go:26
                Error:          Not equal:
                                expected: string(":logo")
                                actual  : <nil>(<nil>)
                Test:           TestColumn
--- FAIL: TestColumn (0.00s)
=== RUN   TestColumnInIsNil
    importable_test.go:33:
                Error Trace:    importable_test.go:33
                Error:          Not equal:
                                expected: string(":created_at")
                                actual  : <nil>(<nil>)
                Test:           TestColumnInIsNil
    importable_test.go:34:
                Error Trace:    importable_test.go:34
                Error:          Not equal:
                                expected: "创建时间"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -创建时间
                                +
                Test:           TestColumnInIsNil
--- FAIL: TestColumnInIsNil (0.00s)
=== RUN   TestFilter
    importable_test.go:41:
                Error Trace:    importable_test.go:41
                Error:          Not equal:
                                expected: "where.name.match"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -where.name.match
                                +
                Test:           TestFilter
--- FAIL: TestFilter (0.00s)
=== RUN   TestRender
    importable_test.go:48:
                Error Trace:    importable_test.go:48
                Error:          Not equal:
                                expected: string(":image")
                                actual  : <nil>(<nil>)
                Test:           TestRender
    importable_test.go:49:
                Error Trace:    importable_test.go:49
                Error:          Not equal:
                                expected: float64(40)
                                actual  : <nil>(<nil>)
                Test:           TestRender
    importable_test.go:50:
                Error Trace:    importable_test.go:50
                Error:          Not equal:
                                expected: float64(60)
                                actual  : <nil>(<nil>)
                Test:           TestRender
--- FAIL: TestRender (0.00s)
=== RUN   TestPage
    importable_test.go:57:
                Error Trace:    importable_test.go:57
                Error:          Not equal:
                                expected: "id"
                                actual  : ""

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1 +1 @@
                                -id
                                +
                Test:           TestPage
--- FAIL: TestPage (0.00s)
=== RUN   TestAPI
    importable_test.go:64:
                Error Trace:    importable_test.go:64
                Error:          Not equal:
                                expected: []interface {}{interface {}(nil), interface {}(nil), 10}
                                actual  : []interface {}(nil)

                                Diff:
                                --- Expected
                                +++ Actual
                                @@ -1,6 +1,2 @@
                                -([]interface {}) (len=3) {
                                - (interface {}) <nil>,
                                - (interface {}) <nil>,
                                - (float64) 10
                                -}
                                +([]interface {}) <nil>

                Test:           TestAPI
--- FAIL: TestAPI (0.00s)
=== RUN   TestWatch
--- PASS: TestWatch (0.00s)
FAIL
2022/04/01 15:03:47 no such file or directory
FAIL    github.com/yaoapp/yao/share     0.075s
FAIL
=== RUN   TestLoad
    store_test.go:22:
                Error Trace:    store_test.go:22
                                                        store_test.go:14
                Error:          Not equal:
                                expected: 1
                                actual  : 0
                Test:           TestLoad
--- FAIL: TestLoad (0.00s)
FAIL
coverage: 36.4% of statements in github.com/yaoapp/yao/store
FAIL    github.com/yaoapp/yao/store     0.127s
FAIL
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 50 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/table     0.161s
FAIL
=== RUN   TestCaptcha
--- PASS: TestCaptcha (0.01s)
PASS
coverage: 34.0% of statements in github.com/yaoapp/yao/user
ok      github.com/yaoapp/yao/user      0.045s  coverage: 34.0% of statements in github.com/yaoapp/yao/user
panic: Connection timeout 5s (sqlite3: ./db/yao.db)

goroutine 21 [running]:
github.com/yaoapp/xun/capsule.(*Manager).AddConnection.func1()
        /da/xun/capsule/capsule.go:86 +0x108
created by github.com/yaoapp/xun/capsule.(*Manager).AddConnection
        /da/xun/capsule/capsule.go:83 +0x2ba
FAIL    github.com/yaoapp/yao/workflow  0.158s
FAIL
=== RUN   TestProcessGetToken
--- FAIL: TestProcessGetToken (0.86s)
panic: {"message":"配置错误 SDK.ServerError\nErrorCode: MissingAccessKeyId\nRecommend: https://troubleshoot.api.aliyun.com?q=MissingAccessKeyId\u0026product=Sts\nRequestId: 1E48ACD5-82B3-55BD-AA5A-36185410D525\nMessage: AccessKeyId is mandatory for this action.","code":400,"context":null} [recovered]
        panic: {"message":"配置错误 SDK.ServerError\nErrorCode: MissingAccessKeyId\nRecommend: https://troubleshoot.api.aliyun.com?q=MissingAccessKeyId\u0026product=Sts\nRequestId: 1E48ACD5-82B3-55BD-AA5A-36185410D525\nMessage: AccessKeyId is mandatory for this action.","code":400,"context":null}

goroutine 41 [running]:
testing.tRunner.func1.2({0x2896d00, 0xc000464480})
        /usr/lib/go/src/testing/testing.go:1389 +0x24e
testing.tRunner.func1()
        /usr/lib/go/src/testing/testing.go:1392 +0x39f
panic({0x2896d00, 0xc000464480})
        /usr/lib/go/src/runtime/panic.go:838 +0x207
github.com/yaoapp/kun/exception.Exception.Throw(...)
        /da/kun/exception/exception.go:111
github.com/yaoapp/yao/xfs.processGetToken(0xc000075ee8?)
        /da/yao/xfs/process.go:113 +0x374
github.com/yaoapp/yao/xfs.TestProcessGetToken(0x0?)
        /da/yao/xfs/process_test.go:35 +0xdd
testing.tRunner(0xc00041f860, 0x29a22b8)
        /usr/lib/go/src/testing/testing.go:1439 +0x102
created by testing.(*T).Run
        /usr/lib/go/src/testing/testing.go:1486 +0x35f
FAIL    github.com/yaoapp/yao/xfs       0.912s
FAIL
root@PW9013436:/da/yao#`

**Comment by evalwhen** [comment]
> 我使用linux环境make报错了，如下

Please remove this useless comment，tks.

**Comment by sanrentai** [comment]
可以调整v8go到之前的提交，某次提交之后，v8go就不支持windows了
