### ISSUE TITLE
如何配置mysql作为数据源

### ISSUE THREAD

**Issue by TomeC** [YaoApp/yao#95]
文档里没找到，请问在哪里可以配置呢

**Comment by 41668895** [comment]
https://yaoapps.com/doc/a.%E4%BB%8B%E7%BB%8D/b.%E5%AE%89%E8%A3%85%E8%B0%83%E8%AF%95

**Comment by TomeC** [comment]
谢谢！

**Comment by athmoon** [comment]
yao init 然后
尝试切换mysql失败（文档更新不及时？）

yao migrate
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x1 addr=0x63 pc=0x7f9b305495ca]

runtime stack:
runtime.throw({0x2594bdf, 0x7f9b0c000d53})
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/panic.go:1198 +0x71
runtime.sigpanic()
        /opt/hostedtoolcache/go/1.17.7/x64/src/runtime/signal_unix.go:719 +0x396

goroutine 24 [syscall]:
runtime.cgocall(0x11ca250, 0xc000060590)
