### ISSUE TITLE
如何修改页面的显示细节，生成的html css js代码在哪里呢，我想自定义的修改前端页面样式

### ISSUE THREAD

**Issue by 7117** [YaoApp/yao#97]

**Comment by 41668895** [comment]
不支持，除非自己编译源代码

**Comment by 41668895** [comment]
也可以自己实现全部前端代码，通过api调用后台逻辑

**Comment by 7117** [comment]
好的

**Comment by 7117** [comment]
> 不支持，除非自己编译源代码

ok，大佬，如果我自己修改源代码的话，比如我想修改下饼图的样式，大体一个怎么样的修改流程呢，样式放在了哪个文件夹呢？

**Comment by 41668895** [comment]
https://github.com/YaoApp/xgen/tree/main/src/pages

**Comment by 7117** [comment]
ok,学到了。
