### ISSUE TITLE
能否向application.log中写入自定义的日志信息？

### ISSUE THREAD

**Issue by liushuainice** [YaoApp/yao#98]
现在不支持的话，以后是否考虑支持？

**Comment by QJAutumn** [comment]
您可以使用log.Error("%v", foo_bar);打印出自定义日志,会在application.log里面看到您的打印信息

**Comment by liushuainice** [comment]
> 您可以使用 log.Error ("% v", foo_bar); 打印出自定义日志，会在 application.log 里面看到您的打印信息

测试不好使,会提示 ReferenceError: log is not defined

**Comment by QJAutumn** [comment]
下载最新版本的https://release-sv-1252011659.cos.na-siliconvalley.myqcloud.com/archives/yao-0.10.0-linux-amd64
